import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { calculateProgress, CHECKLIST_TASK_STATUSES, nextMonth, REVIEW_STATUSES, workflowSummary } from "@/lib/monthly-checklist-service";
import { formatDateTime } from "@/lib/format";
import { addMissingStandardTasksAction, answerChecklistQuestionAction, completeReworkAction, raiseChecklistQuestionAction, reopenPeriodAction, reviewTaskAction, transitionPeriodAction, transferChecklistTaskAction, updateChecklistRolesAction, updateChecklistTaskAction, updatePeriodAction } from "../actions";
import { ToastMessage } from "@/app/components/toast-message";
import { requireUser } from "@/lib/auth";
import { canViewClient } from "@/lib/permissions";
import { OrdoCampusPanel } from "@/app/components/ordo-campus-panel";
import { TaskProcessingForm } from "@/app/components/task-processing-form";
import { TaskTransferForm } from "@/app/components/task-transfer-form";
import { payrollReconciliationSummary } from "@/lib/payroll-reconciliation-service";

type SearchParams = Promise<Record<string,string|string[]|undefined>>;
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";

export default async function MonthlyChecklistDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:SearchParams}){
  const user=await requireUser();
  const id=Number((await params).id);
  const checklist=await prisma.accountingPeriod.findUnique({where:{id},include:{
    client:true,
    tasks:{include:{standardTask:{select:{campusKnowledge:{select:{status:true}}}},sourceTask:{include:{period:{select:{id:true,periodLabel:true}}}},payrollReconciliation:{include:{items:{include:{documents:{select:{status:true}},questions:{select:{status:true}}}}}}},orderBy:[{categorySortOrder:"asc"},{categorySnapshot:"asc"},{sortOrderSnapshot:"asc"},{taskIdSnapshot:"asc"}]},
    history:{include:{checklistTask:{select:{taskIdSnapshot:true}}},orderBy:{occurredAt:"desc"}},
  }});
  if(!checklist)notFound();
  if(!canViewClient(user,checklist))redirect("/zugriff-verweigert?bereich=Monatscheckliste");
  const query=await searchParams;
  const search=one(query.suche).toLocaleLowerCase("de-DE");
  const processingFilter=one(query.bearbeitungsstatus),reviewFilter=one(query.pruefstatus),mandatoryFilter=one(query.pflicht),categoryFilter=one(query.kategorie),originFilter=one(query.herkunft);
  const onlyIssues=one(query.pruefpunkte)==="1",onlyNotes=one(query.notizen)==="1";
  const tasks=checklist.tasks.filter(task=>
    (!search||[task.taskIdSnapshot,task.titleSnapshot,task.processingNote,task.reviewNote].some(value=>value?.toLocaleLowerCase("de-DE").includes(search)))&&
    (!processingFilter||task.status===processingFilter)&&(!reviewFilter||task.reviewStatus===reviewFilter)&&
    (!mandatoryFilter||task.mandatorySnapshot===(mandatoryFilter==="ja"))&&(!categoryFilter||task.categorySnapshot===categoryFilter)&&
    (!originFilter||task.origin===originFilter)&&(!onlyIssues||["Rückfrage","Beanstandung"].includes(task.reviewStatus))&&
    (!onlyNotes||Boolean(task.processingNote||task.reviewNote)));
  const progress=calculateProgress(checklist.tasks),summary=workflowSummary(checklist.tasks),following=nextMonth(checklist.calendarYear,checklist.month);
  const groups=Map.groupBy(tasks,task=>task.categorySnapshot),closed=checklist.processingStatus==="Abgeschlossen";
  const error=one(query.fehler),success=one(query.erfolg);
  return <div>
    <Link className="text-sm font-semibold text-[var(--color-primary-dark)] hover:underline" href="/monatschecklisten">← Zu den Rechnungswesenaufgaben</Link>
    <ToastMessage message={error||(success?success==="uebertragen"?`Die Aufgabe wurde in ${monthName(following.month)} ${following.year} übertragen.`:"Die Monatscheckliste wurde gespeichert.":"")} type={error?"error":"success"} focusId={error?"aufgaben":undefined}/>
    <header className="my-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-[var(--color-primary)]">Mandant {checklist.client.clientNumber}</p><h1 className="mt-2 text-3xl font-bold">{checklist.client.name} · {checklist.periodLabel}</h1></div><a className="button-secondary" href="#verlauf">Verlauf öffnen</a></header>
    <section id="workflow" tabIndex={-1} className="rounded-lg border border-[var(--color-border)] bg-white p-5 shadow-sm">
      <dl className="grid gap-4 md:grid-cols-3 xl:grid-cols-7">
        <Data label="Checklistenstatus" value={checklist.processingStatus}/><Data label="Bearbeiter" value={checklist.processorSnapshot??"–"}/><Data label="Prüfer" value={checklist.reviewerSnapshot??"–"}/><Data label="Kanzleileitung" value={checklist.managementNameSnapshot??"–"}/><Data label="Angemeldet" value={user.fullName}/><Data label="Fortschritt" value={`${progress.percent} %`}/><Data label="Offene Pflicht" value={String(progress.mandatoryOpen)}/><Data label="Offene Prüfpunkte" value={String(summary.openReviewPoints)}/><Data label="Nicht abschließend geprüft" value={String(summary.unreviewed)}/>
      </dl>
      <form action={updatePeriodAction.bind(null,checklist.id)} className="mt-5 grid gap-3 border-t border-[var(--color-border)] pt-4 md:grid-cols-[1fr_auto] md:items-end"><input type="hidden" name="processingStatus" value={checklist.processingStatus}/><Field label="Allgemeiner Checklistenhinweis"><input className="input" name="generalNote" defaultValue={checklist.generalNote??""} disabled={closed}/></Field><button className="button-secondary" disabled={closed}>Hinweis speichern</button></form>
      <div className="mt-5 border-t border-[var(--color-border)] pt-4"><WorkflowActions checklistId={checklist.id} status={checklist.processingStatus} processor={user.fullName} reviewer={user.fullName} summary={summary}/></div>
      {!closed&&user.roles.includes("KANZLEILEITUNG")&&<details className="mt-5 border-t border-[var(--color-border)] pt-4"><summary className="cursor-pointer text-sm font-semibold">Rollenzuordnung dieser Checkliste ändern</summary><form action={updateChecklistRolesAction.bind(null,checklist.id)} className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Bearbeiter"><input className="input" name="processor" defaultValue={checklist.processorSnapshot??""}/></Field><Field label="Prüfer"><input className="input" name="reviewer" defaultValue={checklist.reviewerSnapshot??""}/></Field><Field label="Kanzleileitung"><input className="input" name="managementName" defaultValue={checklist.managementNameSnapshot??""}/></Field><p className="text-sm">Diese Aktion wird ausgeführt von: <strong>{user.fullName}</strong></p><Field label="Änderungsgrund"><textarea className="input" name="reason" required/></Field><button className="button-secondary self-end">Rollenänderung speichern</button></form></details>}
    </section>
    <section id="aufgaben" tabIndex={-1} className="mt-6 rounded-lg border border-[var(--color-border)] bg-white p-4 shadow-sm"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Aufgaben filtern</h2>{!closed&&<form action={addMissingStandardTasksAction.bind(null,checklist.id)}><button className="button-secondary">Fehlende Standardaufgaben übernehmen</button></form>}</div><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <Field label="Suche"><input className="input" name="suche" defaultValue={one(query.suche)} placeholder="ID, Aufgabe oder Notiz"/></Field>
      <Select label="Bearbeitungsstatus" name="bearbeitungsstatus" value={processingFilter} options={CHECKLIST_TASK_STATUSES}/><Select label="Prüfstatus" name="pruefstatus" value={reviewFilter} options={REVIEW_STATUSES}/><Select label="Pflichtaufgabe" name="pflicht" value={mandatoryFilter} options={["ja","nein"]} labels={["Ja","Nein"]}/>
      <Select label="Kategorie" name="kategorie" value={categoryFilter} options={[...new Set(checklist.tasks.map(t=>t.categorySnapshot))]}/><Select label="Herkunft" name="herkunft" value={originFilter} options={[...new Set(checklist.tasks.map(t=>t.origin))]}/>
      <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="pruefpunkte" value="1" defaultChecked={onlyIssues}/> Nur offene Prüfpunkte</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="notizen" value="1" defaultChecked={onlyNotes}/> Nur Aufgaben mit Notiz</label>
      <div className="flex gap-2"><button className="button-primary">Anwenden</button><Link className="button-secondary" href={`/monatschecklisten/${checklist.id}`}>Zurücksetzen</Link></div>
    </form></section>
    <div className="mt-7 space-y-6">{[...groups].map(([category,entries])=><section key={category}><h2 className="mb-3 text-xl font-semibold">{category}</h2><div className="space-y-3">{entries.map(task=><article id={`aufgabe-${task.id}`} key={task.id} className={`rounded-lg border bg-white p-4 shadow-sm ${["Rückfrage","Beanstandung"].includes(task.reviewStatus)?"border-amber-400":"border-[var(--color-border)]"}`}>
      <div className="grid gap-3 xl:grid-cols-[9rem_1fr_10rem_10rem]"><div><div className="font-mono text-xs font-semibold text-[var(--color-primary-dark)]">{task.taskIdSnapshot}</div><div className="mt-1 text-xs text-slate-500">{task.origin}</div>{task.sourceTask&&<Link className="mt-2 inline-flex rounded-full border border-[var(--color-primary)] bg-[var(--color-primary-light)] px-2 py-1 text-xs font-semibold text-[var(--color-primary-dark)]" href={`/monatschecklisten/${task.sourceTask.period.id}#aufgabe-${task.sourceTask.id}`}>↗ Übertrag aus {task.sourceTask.period.periodLabel}</Link>}</div><div><h3 className="font-semibold">{task.titleSnapshot}{task.mandatorySnapshot&&<span className="ml-2 rounded bg-red-100 px-2 py-0.5 text-xs">Pflicht</span>}</h3>{task.workInstructionSnapshot&&<p className="mt-1 text-sm text-slate-600">{task.workInstructionSnapshot}</p>}<OrdoCampusPanel kind="monat" taskId={task.id} activeKnowledge={task.standardTask?.campusKnowledge?.status==="Aktiv"}/></div><Status label="Bearbeitung" value={task.status}/><Status label="Prüfung" value={task.reviewStatus}/></div>
      {task.carriedNoteSourcePeriodLabel&&<Note label="Aus vorheriger Ausführung übernommener Bearbeitungshinweis" text={`Übernommen aus ${task.carriedNoteSourcePeriodLabel}. Status und Prüfstatus wurden nicht übernommen.`}/>}
      {task.reviewIssueStatus==="Offen"&&<Note label="Offene Rückfrage" text={`${task.reviewIssueRaisedByName??"Unbekannt"} (${task.reviewIssueRaisedByRole??"Funktion"}) → ${task.reviewIssueDirectedToName??"Unbekannt"} (${task.reviewIssueDirectedToRole??"Funktion"})`}/>}
      {task.reviewNote&&<Note label={`Prüfnotiz (${task.reviewerInitials??"–"})`} text={task.reviewNote}/>}
      {task.transferReason&&<Note label={`Übertrag nach ${monthName(task.transferTargetMonth??following.month)} ${task.transferTargetYear??following.year}`} text={`${task.transferReason}${task.transferExpectedAction?` · Nächste Handlung: ${task.transferExpectedAction}`:""}`}/>}
      {task.payrollReconciliation&&<PayrollChecklistSummary reconciliation={task.payrollReconciliation}/>}
      {!closed&&(!task.payrollReconciliation||["In Prüfung","Nachbearbeitung"].includes(checklist.processingStatus))&&<TaskForms task={task} status={checklist.processingStatus} checklistId={checklist.id} processor={user.fullName} reviewer={user.fullName} currentUserId={user.id} target={following}/>}
    </article>)}</div></section>)}{!tasks.length&&<p className="rounded border bg-white p-10 text-center">Keine Aufgaben gefunden.</p>}</div>
    {closed&&<section className="mt-7 rounded-lg border border-[var(--color-primary)] bg-[var(--color-primary-light)] p-5"><h2 className="text-xl font-semibold">Folgemonat</h2><p className="mt-1 text-sm">Die neue Monatscheckliste wird erst nach ausdrücklicher Vorschau angelegt.</p><Link className="button-primary mt-3" href={`/monatschecklisten/neu?clientId=${checklist.clientId}&year=${following.year}&month=${following.month}`}>Checkliste für {monthName(following.month)} {following.year} anlegen</Link></section>}
    {closed&&user.roles.includes("KANZLEILEITUNG")&&<section className="mt-7 rounded-lg border-2 border-red-300 bg-red-50 p-5"><h2 className="text-xl font-semibold">Abschluss wieder öffnen</h2><p className="mt-1 text-sm">Die Monatscheckliste wird auf „Nachbearbeitung“ gesetzt. Die Wiederöffnung bleibt im Verlauf sichtbar.</p><form action={reopenPeriodAction.bind(null,checklist.id)} className="mt-4 grid gap-3 md:grid-cols-2"><p className="text-sm">Diese Aktion wird ausgeführt von: <strong>{user.fullName}</strong></p><Field label="Verpflichtende Begründung"><input className="input" name="reason" required/></Field><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="confirmed" required/> Ausdrücklich bestätigen</label><button className="button-primary">Abschluss wieder öffnen</button></form></section>}
    <section id="verlauf" className="mt-8"><h2 className="mb-3 text-xl font-semibold">Fachlicher Verlauf</h2><div className="overflow-x-auto rounded border bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Zeitpunkt","Ereignis","Handelnde Person","Aufgabe","Beschreibung","Vorher","Neu"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{checklist.history.map(entry=><tr className="border-t" key={entry.id}><td className="p-3">{formatDateTime(entry.occurredAt)}</td><td className="p-3 font-semibold">{entry.eventType}</td><td className="p-3">{entry.actorInitials??"–"}</td><td className="p-3">{entry.checklistTask?.taskIdSnapshot??"–"}</td><td className="p-3">{entry.description}</td><td className="p-3">{entry.previousValue??"–"}</td><td className="p-3">{entry.newValue??"–"}</td></tr>)}</tbody></table></div></section>
  </div>;
}

function WorkflowActions({checklistId,status,processor,reviewer,summary}:{checklistId:number;status:string;processor:string;reviewer:string;summary:ReturnType<typeof workflowSummary>}){
  const config=status==="Offen"?["BEGIN_PROCESSING","Bearbeitung beginnen",processor]:status==="In Bearbeitung"?["SUBMIT_REVIEW","Zur Prüfung übergeben",processor]:status==="Zur Prüfung"?["BEGIN_REVIEW","Prüfung beginnen",reviewer]:status==="In Prüfung"?(summary.openReviewPoints?["RETURN_REWORK","Zur Nachbearbeitung zurückgeben",reviewer]:["COMPLETE_REVIEW","Prüfung abschließen",reviewer]):status==="Nachbearbeitung"?["SUBMIT_REVIEW","Erneut zur Prüfung übergeben",processor]:null;
  if(!config)return <p className="text-sm">Die Monatscheckliste ist abgeschlossen und gesperrt.</p>;
  const [action,label,person]=config;
  return <div><div className="mb-3 flex flex-wrap gap-4 text-sm"><span>Erledigt: <b>{summary.done}</b></span><span>Nicht zutreffend: <b>{summary.notApplicable}</b></span><span>Übertragen: <b>{summary.transferred}</b></span><span>Offen Pflicht: <b>{summary.mandatoryOpen}</b></span><span>Nicht abschließend geprüft: <b>{summary.unreviewed}</b></span></div><form action={transitionPeriodAction.bind(null,checklistId,action as Parameters<typeof transitionPeriodAction>[1])} className="flex flex-wrap items-end gap-3"><input type="hidden" name="actorInitials" value={person}/><div className="rounded bg-[var(--color-primary-light)] px-3 py-2 text-sm">Handelnde Person: <strong>{person||"Nicht hinterlegt"}</strong></div><button className="button-primary">{label}</button>{action==="COMPLETE_REVIEW"&&<button className="button-secondary" name="createFollowing" value="1">Abschließen und Folgemonat anlegen</button>}</form></div>;
}
function TaskForms({task,status,checklistId,processor,reviewer,currentUserId,target}:{task:Awaited<ReturnType<typeof prisma.checklistTask.findFirstOrThrow>>;status:string;checklistId:number;processor:string;reviewer:string;currentUserId:number;target:{year:number;month:number}}){
  return <div className="mt-4 grid gap-3 xl:grid-cols-2">
    {["Offen","In Bearbeitung","Nachbearbeitung"].includes(status)&&<TaskProcessingForm action={updateChecklistTaskAction.bind(null,task.id,checklistId)} statuses={CHECKLIST_TASK_STATUSES.filter(v=>v!=="In Folgemonat übertragen")} initialStatus={task.status==="In Folgemonat übertragen"?"Erledigt":task.status} processingNote={task.processingNote} notApplicableReason={task.notApplicableReason} person={processor} allowCarryForward carryProcessingNote={task.carryProcessingNote}/>}
    {["Offen","In Bearbeitung","Nachbearbeitung"].includes(status)&&task.status!=="In Folgemonat übertragen"&&<TaskTransferForm action={transferChecklistTaskAction.bind(null,task.id,checklistId)} targetLabel={`${monthName(target.month)} ${target.year}`} targetYear={target.year} targetMonth={target.month} person={processor}/>}
    {["Offen","In Bearbeitung"].includes(status)&&task.reviewIssueStatus!=="Offen"&&<details className="rounded border border-[var(--color-border)] bg-white p-3"><summary className="cursor-pointer font-semibold text-[var(--color-primary-dark)]">Rückfrage an Prüfer</summary><form action={raiseChecklistQuestionAction.bind(null,task.id,checklistId)} className="mt-3"><Field label="Rückfrage"><textarea className="input min-h-20" name="question" required/></Field><p className="my-2 text-sm">Gerichtet an: <strong>{reviewer||"Prüfer nicht hinterlegt"}</strong></p><button className="button-secondary">Rückfrage senden</button></form></details>}
    {task.reviewIssueStatus==="Offen"&&task.reviewIssueRaisedByRole==="Bearbeiter"&&task.reviewIssueDirectedToUserId===currentUserId&&<form className="rounded border border-[var(--color-primary)] bg-[var(--color-primary-light)] p-3" action={answerChecklistQuestionAction.bind(null,task.id,checklistId)}><h4 className="font-semibold">Rückfrage des Bearbeiters beantworten</h4><Field label="Antwort"><textarea className="input min-h-20" name="answer" required/></Field><button className="button-primary mt-2">Antwort senden</button></form>}
    {status==="In Prüfung"&&<form action={reviewTaskAction.bind(null,task.id,checklistId)} className="rounded border border-[var(--color-primary)] bg-[var(--color-primary-light)] p-3"><h4 className="font-semibold">Prüfung</h4><Field label="Prüfstatus"><select className="input" name="reviewStatus" defaultValue={["Nicht geprüft","Erledigt nach Nachbearbeitung"].includes(task.reviewStatus)?"":task.reviewStatus} required><option value="">Bitte ausdrücklich auswählen</option>{REVIEW_STATUSES.filter(v=>!["Nicht geprüft","Erledigt nach Nachbearbeitung","In Prüfung"].includes(v)).map(value=><option key={value}>{value}</option>)}</select></Field><input type="hidden" name="reviewerInitials" value={reviewer}/><p className="my-2 text-sm">Geprüft von: <strong>{reviewer||"Nicht hinterlegt"}</strong></p><Field label="Prüfnotiz"><textarea className="input min-h-20" name="reviewNote" defaultValue={task.reviewNote??""}/></Field><button className="button-primary mt-2">Prüfung speichern</button></form>}
    {status==="Nachbearbeitung"&&["Rückfrage","Beanstandung"].includes(task.reviewStatus)&&<form action={completeReworkAction.bind(null,task.id,checklistId)} className="rounded border border-amber-300 bg-amber-50 p-3"><h4 className="font-semibold">Prüfpunkt beantworten</h4><Field label="Antwort des Bearbeiters"><textarea className="input min-h-20" name="processorResponse"/></Field><Field label="Bearbeitungsnotiz"><textarea className="input min-h-20" name="processingNote" defaultValue={task.processingNote??""}/></Field><input type="hidden" name="respondedBy" value={processor}/><p className="my-2 text-sm">Beantwortet von: <strong>{processor||"Nicht hinterlegt"}</strong></p><button className="button-primary">Nachbearbeitung erledigt</button></form>}
  </div>;
}
function monthName(month:number){return new Intl.DateTimeFormat("de-DE",{month:"long"}).format(new Date(2026,month-1,1))}
function Data({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>}
function Status({label,value}:{label:string;value:string}){return <div className="text-xs"><span className="font-semibold text-slate-500">{label}</span><div className="mt-1 rounded bg-slate-100 px-2 py-1 font-semibold">{value}</div></div>}
function Note({label,text}:{label:string;text:string}){return <div className="mt-3 rounded border border-amber-200 bg-amber-50 p-3 text-sm"><strong>{label}:</strong> {text}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
function Select({label,name,value,options,labels}:{label:string;name:string;value:string;options:readonly string[];labels?:string[]}){return <Field label={label}><select className="input" name={name} defaultValue={value}><option value="">Nicht filtern</option>{options.map((option,index)=><option key={option} value={option}>{labels?.[index]??option}</option>)}</select></Field>}
function PayrollChecklistSummary({reconciliation}:{reconciliation:{id:number;accountingStatus:string;payrollStatus:string;payrollUserNameSnapshot:string;transferredAt:Date|null;items:Array<{status:string;matterPresent:string;payrollProcessingStatus:string;documentToFollow:boolean;documents:Array<{status:string}>;questions:Array<{status:string}>}>}}){
  const summary=payrollReconciliationSummary(reconciliation.items);
  return <div className="mt-4 rounded-lg border-2 border-[var(--color-primary)] bg-[var(--color-primary-light)] p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Data label="Gesamtstatus Rechnungswesen" value={reconciliation.accountingStatus}/><Data label="Themen geprüft" value={`${summary.reviewed} von ${summary.total}`}/><Data label="Sachverhalte vollständig" value={String(summary.fullyTransferred)}/><Data label="Lohnsachbearbeiter" value={reconciliation.payrollUserNameSnapshot}/><Data label="Offene Lohnrückfragen" value={String(summary.openQuestions)}/><Data label="Lohnstatus" value={reconciliation.payrollStatus}/><Data label="Übergabe" value={reconciliation.transferredAt?formatDateTime(reconciliation.transferredAt):"Noch nicht erfolgt"}/></div><Link className="button-primary mt-4" href={`/fibu-lohn/${reconciliation.id}`}>Abstimmung öffnen</Link></div>
}
