import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { hasRole } from "@/lib/permissions";
import { payrollReconciliationSummary } from "@/lib/payroll-reconciliation-service";
import { ClickableTableRow } from "@/app/components/clickable-table-row";
import { formatDateTime } from "@/lib/format";

type SearchParams=Promise<Record<string,string|string[]|undefined>>;
const one=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]??"":value??"";

export default async function PayrollDashboard({searchParams}:{searchParams:SearchParams}){
  const user=await requireUser();const params=await searchParams;
  const now=new Date();const defaultYear=Number(new Intl.DateTimeFormat("en-CA",{year:"numeric",timeZone:"Europe/Berlin"}).format(now));
  const defaultMonth=Number(new Intl.DateTimeFormat("en-CA",{month:"numeric",timeZone:"Europe/Berlin"}).format(now));
  const year=validYear(Number(one(params.jahr)))?Number(one(params.jahr)):defaultYear;
  const month=validMonth(Number(one(params.monat)))?Number(one(params.monat)):defaultMonth;
  const status=one(params.status),search=one(params.suche).trim();
  const payrollRole=hasRole(user,"LOHNSACHBEARBEITER"),officeWide=hasRole(user,"KANZLEILEITUNG");
  const responsibility=officeWide?{}:payrollRole?{payrollUserId:user.id}:{OR:[{processorUserId:user.id},{reviewerUserId:user.id}]};
  const reconciliations=await prisma.payrollReconciliation.findMany({where:{
    ...responsibility,payrollYear:year,payrollMonth:month,
    ...(status?{payrollStatus:status}:{}),
    ...(search?{client:{OR:[{clientNumber:{contains:search}},{name:{contains:search}}]}}:{}),
  },include:{client:true,items:{include:{documents:{select:{status:true}},questions:{select:{status:true}}}}},orderBy:[{payrollStatus:"asc"},{transferredAt:"asc"},{client:{clientNumber:"asc"}},{client:{name:"asc"}}],take:100});
  const counts=Object.fromEntries(["Neu","Gesehen","Rückfrage offen","Erledigt"].map(value=>[value,reconciliations.filter(item=>item.payrollStatus===value).length]));
  const openQuestions=await prisma.payrollReconciliationQuestion.findMany({where:payrollRole?{OR:[{senderUserId:user.id},{recipientUserId:user.id}],status:{not:"Erledigt durch Lohn"}}:{recipientUserId:user.id,status:"Offen beim Rechnungswesen"},include:{reconciliation:{include:{client:true}},reconciliationItem:true,sender:true,recipient:true},orderBy:{createdAt:"asc"},take:100});
  return <div>
    <header className="mb-6"><p className="text-sm font-semibold uppercase tracking-wider text-[var(--color-primary)]">FiBu-Lohn-Abstimmung</p><h1 className="mt-2 text-3xl font-bold">{payrollRole?"Meine FiBu-Lohn-Abstimmungen":"FiBu-Lohn-Arbeitsübersicht"}</h1><p className="mt-2 text-[var(--color-text-muted)]">{payrollRole?"Ausschließlich Ihre zugeordneten Lohnübergaben. Rechnungswesenchecklisten werden hier nicht bearbeitet.":"Kompakter Einstieg in zugeordnete Abstimmungen und Rückfragen."}</p></header>
    <nav aria-label="Lohnabrechnungsmonat" className="mb-5 flex flex-wrap gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-primary-light)] p-3"><Link className="button-secondary" href={monthHref(year,month,-1)}>← Vorheriger Monat</Link><Link className="button-secondary" href={monthHref(year,month,1)}>Nächster Monat →</Link><span className="ml-auto rounded bg-white px-4 py-2 text-sm font-bold text-[var(--color-primary-dark)]">{monthLabel(year,month)}</span></nav>
    <form className="grid gap-3 rounded-lg border border-[var(--color-border)] bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-5"><Field label="Lohnabrechnungsjahr"><input className="input" name="jahr" type="number" min="2000" max="2100" defaultValue={year}/></Field><Field label="Lohnabrechnungsmonat"><select className="input" name="monat" defaultValue={month}>{Array.from({length:12},(_,index)=><option value={index+1} key={index+1}>{monthLabel(2026,index+1).replace(" 2026","")}</option>)}</select></Field><Field label="Mandantensuche"><input className="input" name="suche" defaultValue={search} placeholder="Nummer oder Name"/></Field><Field label="Lohnstatus"><select className="input" name="status" defaultValue={status}><option value="">Alle</option>{["Neu","Gesehen","Rückfrage offen","Erledigt"].map(value=><option key={value}>{value}</option>)}</select></Field><div className="flex items-end gap-2"><button className="button-primary">Anwenden</button><Link className="button-secondary" href="/fibu-lohn">Zurücksetzen</Link></div></form>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(counts).map(([label,value])=><article className="rounded-lg border border-[var(--color-border)] bg-white p-5 shadow-sm" key={label}><p className="text-sm font-semibold text-[var(--color-text-muted)]">{label}</p><p className="mt-2 text-4xl font-bold text-[var(--color-primary-dark)]">{value}</p></article>)}</section>
    <section className="mt-8"><h2 className="mb-3 text-xl font-bold">Abstimmungen · {reconciliations.length}</h2><div className="overflow-x-auto rounded-lg border border-[var(--color-border)] bg-white"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Mandant","Abrechnungsmonat","Sachverhalte","Belege","Nachreichungen","Rückfragen","Eingang","Rechnungswesenstatus","Lohnstatus"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{reconciliations.map(item=>{const summary=payrollReconciliationSummary(item.items);const href=`/fibu-lohn/${item.id}`;return <ClickableTableRow href={href} className="border-t" key={item.id}><td className="p-3"><Link className="font-semibold text-[var(--color-primary-dark)]" href={href}>{item.client.clientNumber} · {item.client.name}</Link></td><td className="p-3">{monthLabel(item.payrollYear,item.payrollMonth)}</td><td className="p-3">{summary.matters}</td><td className="p-3">{summary.documents}</td><td className="p-3">{summary.openFollowUps}</td><td className="p-3">{summary.openQuestions}</td><td className="p-3">{item.transferredAt?formatDateTime(item.transferredAt):"Noch nicht übergeben"}</td><td className="p-3">{item.accountingStatus}</td><td className="p-3 font-semibold">{item.payrollStatus}</td></ClickableTableRow>})}{!reconciliations.length&&<tr><td colSpan={9} className="p-10 text-center text-[var(--color-text-muted)]">Für den ausgewählten Abrechnungsmonat liegen keine FiBu-Lohn-Abstimmungen vor.</td></tr>}</tbody></table></div></section>
    <section id="rueckfragen" className="mt-8"><h2 className="mb-3 text-xl font-bold">Offene Rückfragen · {openQuestions.length}</h2><div className="space-y-3">{openQuestions.map(question=><Link className="block rounded-lg border border-[var(--color-border)] bg-white p-4 shadow-sm hover:bg-[var(--color-primary-light)]" href={`/fibu-lohn/${question.reconciliationId}#thema-${question.reconciliationItemId}`} key={question.id}><div className="flex flex-wrap justify-between gap-2"><strong>{question.reconciliation.client.clientNumber} · {question.reconciliation.client.name}</strong><span className="text-sm">{question.status}</span></div><p className="mt-2 text-sm"><strong>{question.reconciliationItem.topicTitleSnapshot}:</strong> {question.message}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{question.sender.fullName} · {formatDateTime(question.createdAt)}</p></Link>)}{!openQuestions.length&&<p className="rounded border border-[var(--color-border)] bg-white p-6 text-sm text-[var(--color-text-muted)]">Derzeit bestehen keine offenen Lohnrückfragen.</p>}</div></section>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
function validYear(value:number){return Number.isInteger(value)&&value>=2000&&value<=2100}
function validMonth(value:number){return Number.isInteger(value)&&value>=1&&value<=12}
function monthLabel(year:number,month:number){return new Intl.DateTimeFormat("de-DE",{month:"long",year:"numeric",timeZone:"Europe/Berlin"}).format(new Date(Date.UTC(year,month-1,15)))}
function monthHref(year:number,month:number,offset:number){const date=new Date(Date.UTC(year,month-1+offset,15));return `/fibu-lohn?jahr=${date.getUTCFullYear()}&monat=${date.getUTCMonth()+1}`}
