import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { annualProgress, ANNUAL_STATUSES } from "@/lib/annual-checklist-service";
import { canManageClients, canViewAnnualChecklist } from "@/lib/permissions";
import { ClickableTableRow } from "@/app/components/clickable-table-row";
import { formatDate } from "@/lib/format";
import { AccountingModuleTabs } from "@/app/components/module-tabs";

const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";
export default async function AnnualOverview({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const user=await requireRole("MITARBEITER","PRUEFER","KANZLEILEITUNG","MANDANTEN_VERWALTEN"),query=await searchParams;
  const year=Number(one(query.jahr))||new Date().getFullYear()-1,status=one(query.status),search=one(query.suche).toLowerCase(),processor=one(query.bearbeiter),reviewer=one(query.pruefer),management=one(query.kanzleileitung),legal=one(query.rechtsform),profit=one(query.gewinn),onlyMandatory=one(query.pflicht)==="1",onlyReview=one(query.pruefpunkte)==="1",onlyOpenMonths=one(query.monate)==="1";
  const all=await prisma.annualChecklist.findMany({where:{fiscalYear:year,...(status?{status}:{})},include:{client:{include:{periods:{where:{calendarYear:year,checklistType:"Monat"},select:{processingStatus:true}}}},tasks:true},orderBy:[{updatedAt:"desc"}]});
  const rows=all.filter(item=>{const p=annualProgress(item.tasks),openMonths=item.client.periods.some(month=>month.processingStatus!=="Abgeschlossen");return canViewAnnualChecklist(user,item)&&(!search||`${item.client.clientNumber} ${item.client.name}`.toLowerCase().includes(search))&&(!processor||item.processorNameSnapshot===processor)&&(!reviewer||item.reviewerNameSnapshot===reviewer)&&(!management||item.managementNameSnapshot===management)&&(!legal||item.legalFormSnapshot===legal)&&(!profit||item.profitDeterminationSnapshot===profit)&&(!onlyMandatory||p.mandatoryOpen>0)&&(!onlyReview||p.openReviewPoints>0)&&(!onlyOpenMonths||openMonths)});
  const unique=(values:string[])=>[...new Set(values)].sort();
  return <div><AccountingModuleTabs active="abschluss"/><header className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-[var(--color-primary)]">Abschlussbearbeitung</p><h1 className="mt-2 text-3xl font-bold">Jahresabschlussaufgaben</h1><p className="mt-2 text-sm text-slate-600">Stichtagsbezogene Aufgaben für die Jahresabschlussbearbeitung.</p></div>{canManageClients(user)&&<Link className="button-primary" href="/jahresabschluesse/neu">Jahresabschlusscheckliste anlegen</Link>}</header>
  <form className="grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Wirtschaftsjahr"><input className="input" name="jahr" type="number" defaultValue={year}/></Field><Field label="Mandant"><input className="input" name="suche" defaultValue={one(query.suche)} placeholder="Nummer oder Name"/></Field><Select label="Bearbeiter" name="bearbeiter" value={processor} options={unique(all.map(i=>i.processorNameSnapshot))}/><Select label="Prüfer" name="pruefer" value={reviewer} options={unique(all.map(i=>i.reviewerNameSnapshot))}/><Select label="Kanzleileitung" name="kanzleileitung" value={management} options={unique(all.map(i=>i.managementNameSnapshot))}/><Select label="Status" name="status" value={status} options={[...ANNUAL_STATUSES]}/><Select label="Rechtsform" name="rechtsform" value={legal} options={unique(all.map(i=>i.legalFormSnapshot))}/><Select label="Gewinnermittlungsart" name="gewinn" value={profit} options={unique(all.map(i=>i.profitDeterminationSnapshot))}/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="pflicht" value="1" defaultChecked={onlyMandatory}/> Nur offene Pflichtaufgaben</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="pruefpunkte" value="1" defaultChecked={onlyReview}/> Nur offene Prüfpunkte</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="monate" value="1" defaultChecked={onlyOpenMonths}/> Nur mit offenen Monatschecklisten</label><div className="flex items-end gap-2"><button className="button-primary">Anwenden</button><Link className="button-secondary" href="/jahresabschluesse">Zurücksetzen</Link></div></form>
  <div className="mt-6 overflow-x-auto rounded-lg border bg-white"><table className="w-full min-w-[1400px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Mandant","Wirtschaftsjahr","Bearbeiter","Prüfer","Kanzleileitung","Status","Fortschritt","Offene Pflicht","Offene Prüfpunkte","Monate vollständig","Letzte Änderung"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(item=>{const p=annualProgress(item.tasks),monthsComplete=item.client.periods.length===12&&item.client.periods.every(month=>month.processingStatus==="Abgeschlossen");return <ClickableTableRow key={item.id} href={`/jahresabschluesse/${item.id}`} className="border-t"><td className="p-3"><Link className="font-semibold text-[var(--color-primary-dark)]" href={`/jahresabschluesse/${item.id}`}>{item.client.clientNumber} · {item.client.name}</Link></td><td className="p-3">{item.fiscalYear}</td><td className="p-3">{item.processorNameSnapshot}</td><td className="p-3">{item.reviewerNameSnapshot}</td><td className="p-3">{item.managementNameSnapshot}</td><td className="p-3">{item.status}</td><td className="p-3">{p.completed}/{p.total} · {p.percent} %</td><td className="p-3">{p.mandatoryOpen}</td><td className="p-3">{p.openReviewPoints}</td><td className="p-3">{monthsComplete?"Ja":"Nein"}</td><td className="p-3">{formatDate(item.updatedAt)}</td></ClickableTableRow>})}{!rows.length&&<tr><td colSpan={11} className="p-10 text-center text-slate-500">Keine Jahresabschlussaufgaben für diese Auswahl.</td></tr>}</tbody></table></div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
function Select({label,name,value,options}:{label:string;name:string;value:string;options:string[]}){return <Field label={label}><select className="input" name={name} defaultValue={value}><option value="">Alle</option>{options.map(option=><option key={option}>{option}</option>)}</select></Field>}
