import type { Prisma } from "@prisma/client";
import Link from "next/link";
import { AccountingModuleTabs } from "@/app/components/module-tabs";
import { ActiveFilterChips } from "@/app/components/active-filter-chips";
import { ClickableTableRow } from "@/app/components/clickable-table-row";
import { annualProgress, ANNUAL_STATUSES } from "@/lib/annual-checklist-service";
import { requireRole } from "@/lib/auth";
import { berlinCalendarMonth, isOlderThanSixMonths } from "@/lib/dashboard-responsibility";
import { annualDashboardResponsibility } from "@/lib/dashboard-responsibility";
import { formatDate } from "@/lib/format";
import { canManageClients, canViewAnnualChecklist } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";

const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";
export default async function AnnualOverview({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const user=await requireRole("MITARBEITER","PRUEFER","KANZLEILEITUNG","MANDANTEN_VERWALTEN"),query=await searchParams;
  const view=["offen","abgeschlossen","alle"].includes(one(query.ansicht))?one(query.ansicht):"offen";
  const workType=one(query.arbeitsart);
  const year=one(query.jahr),status=one(query.status),search=one(query.suche).toLowerCase(),processor=one(query.bearbeiter),reviewer=one(query.pruefer),management=one(query.kanzleileitung),legal=one(query.rechtsform),profit=one(query.gewinn),onlyMandatory=one(query.pflicht)==="1",onlyReview=one(query.pruefpunkte)==="1",onlyOpenMonths=one(query.monate)==="1";
  const historical=view!=="offen";
  const state=view==="offen"?{not:"Freigegeben"}:view==="abgeschlossen"?"Freigegeben":undefined;
  const all=await prisma.annualChecklist.findMany({where:{fiscalYear:historical&&year?Number(year):undefined,status:status||state},include:{client:{include:{periods:{where:{checklistType:"Monat"},select:{calendarYear:true,processingStatus:true}}}},tasks:true},orderBy:view==="offen"?[{fiscalYear:"asc"},{updatedAt:"asc"}]:[{fiscalYear:"desc"},{updatedAt:"desc"}],take:201});
  const rows=all.filter(item=>{const p=annualProgress(item.tasks),openMonths=item.client.periods.some(month=>month.calendarYear===item.fiscalYear&&month.processingStatus!=="Abgeschlossen"),responsibility=annualDashboardResponsibility(item.status,user.id,item);return canViewAnnualChecklist(user,item)&&(!workType||(workType==="processing"&&responsibility==="BEARBEITUNG_AKTIV")||(workType==="review"&&responsibility==="PRUEFUNG_AKTIV")||(workType==="release"&&responsibility==="FREIGABE_AKTIV"))&&(!search||`${item.client.clientNumber} ${item.client.name}`.toLowerCase().includes(search))&&(!processor||item.processorNameSnapshot===processor)&&(!reviewer||item.reviewerNameSnapshot===reviewer)&&(!management||item.managementNameSnapshot===management)&&(!legal||item.legalFormSnapshot===legal)&&(!profit||item.profitDeterminationSnapshot===profit)&&(!onlyMandatory||p.mandatoryOpen>0)&&(!onlyReview||p.openReviewPoints>0)&&(!onlyOpenMonths||openMonths)}).slice(0,200);
  const reference=berlinCalendarMonth();
  const older=view==="offen"?rows.filter(item=>isOlderThanSixMonths(item.fiscalYear,12,reference.year,reference.month)):[];
  const current=view==="offen"?rows.filter(item=>!older.includes(item)):rows;
  const unique=(values:string[])=>[...new Set(values)].sort((a,b)=>a.localeCompare(b,"de-DE"));
  const advanced=[year,processor,reviewer,management,legal,profit,onlyMandatory,onlyReview,onlyOpenMonths].filter(Boolean).length;
  return <div><AccountingModuleTabs active="abschluss"/><header className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-[var(--color-primary)]">Abschlussbearbeitung</p><h1 className="mt-2 text-3xl font-bold">Jahresabschlussaufgaben</h1><p className="mt-2 text-sm text-slate-600">Offene Aufgaben werden wirtschaftsjahrübergreifend nach Verantwortung angezeigt.</p></div>{canManageClients(user)&&<Link className="button-primary" href="/jahresabschluesse/neu">Jahresabschlusscheckliste anlegen</Link>}</header>
  <ViewTabs active={view}/>
  <form className="rounded-lg border bg-white p-4"><input type="hidden" name="ansicht" value={view}/>{workType&&<input type="hidden" name="arbeitsart" value={workType}/>}<div className="flex flex-wrap items-end gap-3"><Field label="Mandant"><input className="input min-w-64" name="suche" defaultValue={one(query.suche)} placeholder="Nummer oder Name"/></Field><Select label="Status" name="status" value={status} options={(view==="offen"?ANNUAL_STATUSES.filter(value=>value!=="Freigegeben"):view==="abgeschlossen"?["Freigegeben"]:[...ANNUAL_STATUSES])}/><button className="button-primary">Anwenden</button><Link className="button-secondary" href={`/jahresabschluesse?ansicht=${view}`}>Zurücksetzen</Link>{workType&&<span className="rounded-full bg-[var(--color-primary-light)] px-3 py-2 text-xs font-semibold text-[var(--color-primary-dark)]">Meine {workType==="review"?"Prüfung":workType==="release"?"Freigabe":"Bearbeitung"}</span>}</div><details className="mt-3 border-t pt-3" open={advanced>0}><summary className="cursor-pointer text-sm font-semibold text-[var(--color-primary-dark)]">Weitere Filter{advanced?` · ${advanced}`:""}</summary><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{historical&&<Field label="Wirtschaftsjahr"><input className="input" name="jahr" type="number" defaultValue={year}/></Field>}<Select label="Bearbeiter" name="bearbeiter" value={processor} options={unique(all.map(i=>i.processorNameSnapshot))}/><Select label="Prüfer" name="pruefer" value={reviewer} options={unique(all.map(i=>i.reviewerNameSnapshot))}/><Select label="Kanzleileitung" name="kanzleileitung" value={management} options={unique(all.map(i=>i.managementNameSnapshot))}/><Select label="Rechtsform" name="rechtsform" value={legal} options={unique(all.map(i=>i.legalFormSnapshot))}/><Select label="Gewinnermittlungsart" name="gewinn" value={profit} options={unique(all.map(i=>i.profitDeterminationSnapshot))}/></div><div className="mt-3 flex flex-wrap gap-4 text-sm font-semibold"><Check name="pflicht" checked={onlyMandatory}>Nur offene Pflichtaufgaben</Check><Check name="pruefpunkte" checked={onlyReview}>Nur offene Prüfpunkte</Check><Check name="monate" checked={onlyOpenMonths}>Nur mit offenen Monatschecklisten</Check></div></details></form>
  <ActiveFilterChips basePath="/jahresabschluesse" params={query} filters={[
    {key:"suche",label:`Suche: ${one(query.suche)}`},{key:"status",label:`Status: ${status}`},{key:"jahr",label:`Jahr: ${year}`},{key:"bearbeiter",label:`Bearbeiter: ${processor}`},{key:"pruefer",label:`Prüfer: ${reviewer}`},{key:"kanzleileitung",label:`Kanzleileitung: ${management}`},{key:"rechtsform",label:`Rechtsform: ${legal}`},{key:"gewinn",label:`Gewinnermittlung: ${profit}`},{key:"pflicht",label:"Nur offene Pflichtaufgaben",active:onlyMandatory},{key:"pruefpunkte",label:"Nur offene Prüfpunkte",active:onlyReview},{key:"monate",label:"Nur mit offenen Monatschecklisten",active:onlyOpenMonths},{key:"arbeitsart",label:`Meine ${workType==="review"?"Prüfung":workType==="release"?"Freigabe":"Bearbeitung"}`,active:Boolean(workType)},
  ]}/>
  <p className="mb-3 mt-5 text-sm text-[var(--color-text-muted)]">{rows.length}{all.length>200?"+":""} Vorgänge · Anzeige auf 200 begrenzt</p>
  <AnnualTable title={view==="offen"?"Aktuelle offene Vorgänge":view==="abgeschlossen"?"Abgeschlossene Vorgänge":"Alle Vorgänge"} rows={current}/>
  {view==="offen"&&<div className="mt-8"><AnnualTable title="Ältere offene Vorgänge" rows={older} note="Mehr als sechs Monate nach dem Ende des Wirtschaftsjahres weiterhin offen."/></div>}
  </div>
}

type AnnualRow=Prisma.AnnualChecklistGetPayload<{include:{client:{include:{periods:{select:{calendarYear:true;processingStatus:true}}}};tasks:true}}>;
function AnnualTable({title,rows,note}:{title:string;rows:AnnualRow[];note?:string}){return <section><h2 className="text-xl font-bold text-[var(--color-primary-dark)]">{title} · {rows.length}</h2>{note&&<p className="mb-3 mt-1 text-sm text-[var(--color-text-muted)]">{note}</p>}<div className={`${note?"":"mt-3"} overflow-x-auto rounded-lg border bg-white`}><table className="w-full min-w-[1400px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Mandant","Wirtschaftsjahr","Bearbeiter","Prüfer","Kanzleileitung","Status","Fortschritt","Offene Pflicht","Offene Prüfpunkte","Monate vollständig","Letzte Änderung"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(item=>{const p=annualProgress(item.tasks),periods=item.client.periods.filter(month=>month.calendarYear===item.fiscalYear),monthsComplete=periods.length===12&&periods.every(month=>month.processingStatus==="Abgeschlossen");return <ClickableTableRow key={item.id} href={`/jahresabschluesse/${item.id}`} className="border-t"><td className="p-3"><Link className="font-semibold text-[var(--color-primary-dark)]" href={`/jahresabschluesse/${item.id}`}>{item.client.clientNumber} · {item.client.name}</Link></td><td className="p-3">{item.fiscalYear}</td><td className="p-3">{item.processorNameSnapshot}</td><td className="p-3">{item.reviewerNameSnapshot}</td><td className="p-3">{item.managementNameSnapshot}</td><td className="p-3">{item.status}</td><td className="p-3">{p.completed}/{p.total} · {p.percent} %</td><td className="p-3">{p.mandatoryOpen}</td><td className="p-3">{p.openReviewPoints}</td><td className="p-3">{monthsComplete?"Ja":"Nein"}</td><td className="p-3">{formatDate(item.updatedAt)}</td></ClickableTableRow>})}{!rows.length&&<tr><td colSpan={11} className="p-10 text-center text-slate-500">Keine Jahresabschlussaufgaben für diese Auswahl.</td></tr>}</tbody></table></div></section>}
function ViewTabs({active}:{active:string}){return <nav aria-label="Bearbeitungsstatus" className="mb-4 flex gap-2">{[["offen","Offen"],["abgeschlossen","Abgeschlossen"],["alle","Alle"]].map(([value,label])=><Link aria-current={active===value?"page":undefined} className={active===value?"button-primary":"button-secondary"} href={`/jahresabschluesse?ansicht=${value}`} key={value}>{label}</Link>)}</nav>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
function Select({label,name,value,options}:{label:string;name:string;value:string;options:readonly string[]}){return <Field label={label}><select className="input min-w-44" name={name} defaultValue={value}><option value="">Alle</option>{options.map(option=><option key={option}>{option}</option>)}</select></Field>}
function Check({name,checked,children}:{name:string;checked:boolean;children:React.ReactNode}){return <label className="flex items-center gap-2"><input type="checkbox" name={name} value="1" defaultChecked={checked}/>{children}</label>}
