import { afterAll,beforeEach,describe,expect,it } from "vitest";
import { prisma } from "@/lib/prisma";
import {
 annualProgress,createAnnualChecklist,reopenAnnualChecklist,reviewAnnualTask,transitionAnnualChecklist,updateAnnualTask,
} from "@/lib/annual-checklist-service";
import type { AuthUser } from "@/lib/permissions";

let processor:AuthUser,reviewer:AuthUser,management:AuthUser,admin:AuthUser,clientId:number,categoryId:number;
beforeEach(async()=>{
 await prisma.functionSeparationException.deleteMany();
 await prisma.annualWorkflowHistory.deleteMany();await prisma.annualChecklistTask.deleteMany();await prisma.annualChecklist.deleteMany();await prisma.customAnnualTask.deleteMany();
 await prisma.workflowHistory.deleteMany();await prisma.checklistTask.deleteMany();await prisma.accountingPeriod.deleteMany();await prisma.customClientTask.deleteMany();await prisma.annualProfile.deleteMany();await prisma.client.deleteMany();await prisma.standardTask.deleteMany();await prisma.taskCategory.deleteMany();await prisma.session.deleteMany();await prisma.userRole.deleteMany();await prisma.user.deleteMany();
 processor=await makeUser("bearbeiter","Künstliche Bearbeitung",["MITARBEITER"]);reviewer=await makeUser("pruefer","Künstliche Prüfung",["PRUEFER"]);management=await makeUser("leitung","Künstliche Leitung",["KANZLEILEITUNG"]);admin=await makeUser("admin","Künstliche Administration",["ADMINISTRATOR"]);
 categoryId=(await prisma.taskCategory.create({data:{name:"Künstlicher Jahresabschluss",sortOrder:10}})).id;
 clientId=(await prisma.client.create({data:{clientNumber:"JA-100",name:"Künstlicher Jahresabschlussmandant",cadence:"monatlich",vatFilingPeriod:"Monatlich",processor:processor.fullName,reviewer:reviewer.fullName,managementName:management.fullName,processorUserId:processor.id,reviewerUserId:reviewer.id,managementUserId:management.id}})).id;
 await prisma.annualProfile.create({data:{clientId,calendarYear:2025,legalFormGroup:"Kapitalgesellschaft",profitDeterminationMethod:"Bilanzierung",hasFixedAssets:true}});
 await prisma.standardTask.create({data:{taskId:"JA-AUTO-001",active:true,checklistType:"Jahresabschluss",categoryId,title:"Künstliche Pflichtaufgabe",mandatory:true,rhythm:"Jährlich",legalFormGroups:"Alle",profitDeterminationMethods:"Alle",cashCondition:"Alle",payrollCondition:"Alle",fixedAssetsCondition:"Alle",receivablesPayablesCondition:"Alle",loansCondition:"Alle",vatCondition:"Alle",permanentExtensionCondition:"Alle",professionalVersion:"TEST"}});
});
afterAll(async()=>{await prisma.annualWorkflowHistory.deleteMany();await prisma.annualChecklistTask.deleteMany();await prisma.annualChecklist.deleteMany();await prisma.functionSeparationException.deleteMany();await prisma.$disconnect()});

describe("Jahresabschlussanlage und Snapshots",()=>{
 it("erlaubt pro Mandant und Wirtschaftsjahr nur eine Checkliste",async()=>{await createAnnualChecklist(clientId,2025,processor);await expect(createAnnualChecklist(clientId,2025,processor)).rejects.toMatchObject({code:"CHECKLIST_EXISTS"})});
 it("verlangt ein Jahresprofil",async()=>{await expect(createAnnualChecklist(clientId,2024,processor)).rejects.toMatchObject({code:"PROFILE_MISSING"})});
 it("speichert Bearbeiter, Prüfer und Kanzleileitung als Snapshot",async()=>{const item=await createAnnualChecklist(clientId,2025,processor);const saved=await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}});expect([saved.processorUserId,saved.reviewerUserId,saved.managementUserId]).toEqual([processor.id,reviewer.id,management.id]);expect(saved.processorNameSnapshot).toBe(processor.fullName)});
 it("erlaubt identische Rollen-Snapshots bei passender fachlicher Rolle",async()=>{const multi=await makeUser("mehrfach","Künstliche Mehrfachrolle",["MITARBEITER","PRUEFER","KANZLEILEITUNG"]);await prisma.client.update({where:{id:clientId},data:{processorUserId:multi.id,reviewerUserId:multi.id,managementUserId:multi.id,processor:multi.fullName,reviewer:multi.fullName,managementName:multi.fullName}});const item=await createAnnualChecklist(clientId,2025,multi);const saved=await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}});expect([saved.processorUserId,saved.reviewerUserId,saved.managementUserId]).toEqual([multi.id,multi.id,multi.id])});
});

describe("Drei Rollen und Freigabe",()=>{
 it("beginnt Bearbeitung und Prüfung erst mit der jeweils ersten erfolgreichen Fachänderung",async()=>{const {item,task}=await setup();expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).status).toBe("Offen");await updateAnnualTask(task.id,{status:"Erledigt",processingNote:"Künstlich bearbeitet",notApplicableReason:""},processor);expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).status).toBe("In Vorbereitung");await updateAnnualTask(task.id,{status:"Erledigt",processingNote:"Künstlich bearbeitet",notApplicableReason:""},processor);expect(await prisma.annualWorkflowHistory.count({where:{annualChecklistId:item.id,eventType:"Bearbeitung automatisch begonnen"}})).toBe(1);await transitionAnnualChecklist(item.id,"SUBMIT_REVIEW",processor);await expect(reviewAnnualTask(task.id,{reviewStatus:"Beanstandung",reviewNote:""},reviewer)).rejects.toMatchObject({code:"REASON_REQUIRED"});expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).status).toBe("Zur Prüfung");await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:"Künstlich geprüft"},reviewer);expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).status).toBe("In Prüfung");expect(await prisma.annualWorkflowHistory.count({where:{annualChecklistId:item.id,eventType:"Prüfung automatisch begonnen"}})).toBe(1)});
 it("Bearbeiter bearbeitet eigene, aber keine fremde Aufgabe",async()=>{const {task}=await setup();await updateAnnualTask(task.id,{status:"Erledigt",processingNote:"Künstlich erledigt",notApplicableReason:""},processor);await expect(updateAnnualTask(task.id,{status:"Offen",processingNote:"",notApplicableReason:""},reviewer)).rejects.toMatchObject({code:"NOT_ALLOWED"})});
 it("Bearbeiter kann nicht prüfen, zugeordneter Prüfer schon",async()=>{const {item,task}=await readyInReview();await expect(reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:""},processor)).rejects.toMatchObject({code:"NOT_ALLOWED"});await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:""},reviewer);expect((await prisma.annualChecklistTask.findUniqueOrThrow({where:{id:task.id}})).reviewStatus).toBe("In Ordnung");expect(item.status).toBe("In Prüfung")});
 it("Prüfer schließt fachlich ab, aber nicht endgültig frei",async()=>{const {item,task}=await readyInReview();await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:""},reviewer);await transitionAnnualChecklist(item.id,"PROFESSIONAL_COMPLETE",reviewer);await transitionAnnualChecklist(item.id,"SUBMIT_RELEASE",reviewer);await expect(transitionAnnualChecklist(item.id,"RELEASE",reviewer)).rejects.toMatchObject({code:"NOT_ALLOWED"})});
 it("Kanzleileitung gibt eine zugeordnete Checkliste frei",async()=>{const item=await readyForRelease();await transitionAnnualChecklist(item.id,"RELEASE",management,"Künstliche Freigabe");expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).releaseUserId).toBe(management.id)});
 it("Administrator kann nicht allein freigeben",async()=>{const item=await readyForRelease();await expect(transitionAnnualChecklist(item.id,"RELEASE",admin)).rejects.toMatchObject({code:"NOT_ALLOWED"})});
 it("verhindert fachlichen Abschluss mit offenen Pflichtaufgaben",async()=>{const item=await createAnnualChecklist(clientId,2025,processor);await transitionAnnualChecklist(item.id,"BEGIN",processor);await expect(transitionAnnualChecklist(item.id,"SUBMIT_REVIEW",processor)).rejects.toMatchObject({code:"MANDATORY_OPEN"})});
 it("verhindert Abschluss mit offenem Prüfpunkt",async()=>{const {item,task}=await readyInReview();await reviewAnnualTask(task.id,{reviewStatus:"Rückfrage",reviewNote:"Künstliche Frage"},reviewer);await expect(transitionAnnualChecklist(item.id,"PROFESSIONAL_COMPLETE",reviewer)).rejects.toMatchObject({code:"REVIEW_POINTS_OPEN"})});
 it("sperrt freigegebene Aufgaben",async()=>{const item=await readyForRelease();await transitionAnnualChecklist(item.id,"RELEASE",management);const task=await prisma.annualChecklistTask.findFirstOrThrow({where:{annualChecklistId:item.id}});await expect(updateAnnualTask(task.id,{status:"Offen",processingNote:"",notApplicableReason:""},processor)).rejects.toMatchObject({code:"LOCKED"})});
 it("Wiederöffnung verlangt Kanzleileitung und Begründung",async()=>{const item=await readyForRelease();await transitionAnnualChecklist(item.id,"RELEASE",management);await expect(reopenAnnualChecklist(item.id,"",management)).rejects.toMatchObject({code:"REASON_REQUIRED"});await expect(reopenAnnualChecklist(item.id,"Grund",reviewer)).rejects.toMatchObject({code:"NOT_ALLOWED"});await reopenAnnualChecklist(item.id,"Künstlicher Grund",management);expect((await prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})).status).toBe("Nachbearbeitung")});
 it("Verlauf speichert Benutzer und Rollensnapshot",async()=>{const item=await createAnnualChecklist(clientId,2025,processor);const entry=await prisma.annualWorkflowHistory.findFirstOrThrow({where:{annualChecklistId:item.id}});expect(entry.actorUserId).toBe(processor.id);expect(entry.actorRoleSnapshot).toContain("MITARBEITER")});
 it("berechnet Fortschritt einheitlich",()=>expect(annualProgress([{status:"Erledigt",mandatorySnapshot:true,reviewStatus:"In Ordnung"},{status:"Offen",mandatorySnapshot:true,reviewStatus:"Rückfrage"}])).toEqual({total:2,completed:1,percent:50,mandatoryOpen:1,openReviewPoints:1}));
});

describe("Personengleiche Funktionszuordnung",()=>{
 it("führt alle Prozessstufen derselben Person getrennt aus",async()=>{const multi=await makeUser("mehrfach","Künstliche Mehrfachrolle",["MITARBEITER","PRUEFER","KANZLEILEITUNG"]);await prisma.client.update({where:{id:clientId},data:{processorUserId:multi.id,reviewerUserId:multi.id,managementUserId:multi.id,processor:multi.fullName,reviewer:multi.fullName,managementName:multi.fullName}});const annual=await createAnnualChecklist(clientId,2025,multi);const task=await prisma.annualChecklistTask.findFirstOrThrow({where:{annualChecklistId:annual.id}});await expect(transitionAnnualChecklist(annual.id,"RELEASE",multi)).rejects.toMatchObject({code:"NOT_ALLOWED"});await updateAnnualTask(task.id,{status:"Erledigt",processingNote:"Künstlich bearbeitet.",notApplicableReason:""},multi);await transitionAnnualChecklist(annual.id,"SUBMIT_REVIEW",multi);await transitionAnnualChecklist(annual.id,"BEGIN_REVIEW",multi);await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:"Künstlich geprüft."},multi);await transitionAnnualChecklist(annual.id,"PROFESSIONAL_COMPLETE",multi);await transitionAnnualChecklist(annual.id,"SUBMIT_RELEASE",multi);await transitionAnnualChecklist(annual.id,"RELEASE",multi);const entries=await prisma.annualWorkflowHistory.findMany({where:{annualChecklistId:annual.id}});expect(entries.some(entry=>entry.description.includes("Funktion Bearbeiter"))).toBe(true);expect(entries.some(entry=>entry.description.includes("Funktion Prüfer"))).toBe(true);expect(entries.some(entry=>entry.description.includes("Funktion Kanzleileitung"))).toBe(true);expect(entries.every(entry=>entry.functionSeparationExceptionId===null)).toBe(true)});
});

async function makeUser(username:string,fullName:string,roles:AuthUser["roles"]):Promise<AuthUser>{const user=await prisma.user.create({data:{username,fullName,passwordHash:"künstlicher-testhash",active:true,mustChangePassword:false,roles:{create:roles.map(role=>({role}))}}});return{id:user.id,username,fullName,active:true,mustChangePassword:false,roles}}
async function setup(){const item=await createAnnualChecklist(clientId,2025,processor);const task=await prisma.annualChecklistTask.findFirstOrThrow({where:{annualChecklistId:item.id}});return{item,task}}
async function readyInReview(){const result=await setup();await updateAnnualTask(result.task.id,{status:"Erledigt",processingNote:"Künstlich erledigt",notApplicableReason:""},processor);await transitionAnnualChecklist(result.item.id,"SUBMIT_REVIEW",processor);await transitionAnnualChecklist(result.item.id,"BEGIN_REVIEW",reviewer);return{...result,item:await prisma.annualChecklist.findUniqueOrThrow({where:{id:result.item.id}})}}
async function readyForRelease(){const {item,task}=await readyInReview();await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:"Künstlich geprüft"},reviewer);await transitionAnnualChecklist(item.id,"PROFESSIONAL_COMPLETE",reviewer);await transitionAnnualChecklist(item.id,"SUBMIT_RELEASE",reviewer);return prisma.annualChecklist.findUniqueOrThrow({where:{id:item.id}})}
