import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { prisma } from "@/lib/prisma";
import type { AuthUser } from "@/lib/permissions";
import { canManageOrdoCampus, canReadCampusReviewerGuidance } from "@/lib/permissions";
import { archiveKnowledgeContent, knowledgeContentLinkSchema, KnowledgePlatformError, recordKnowledgeView, saveKnowledgeArea, saveKnowledgeContent, setKnowledgeRead } from "@/lib/knowledge-platform-service";
import { provisionKnowledgePlatformFromLegacy } from "@/lib/knowledge-platform-migration";

let manager:AuthUser,reader:AuthUser,reviewer:AuthUser,admin:AuthUser,payroll:AuthUser,taskIds:number[],topicId:number,areaIds:number[];
async function clean(){
  await prisma.knowledgeUserProgress.deleteMany();
  await prisma.knowledgeLearningPathItem.deleteMany();
  await prisma.knowledgeLearningPath.deleteMany();
  await prisma.knowledgeContentTag.deleteMany();
  await prisma.knowledgeTag.deleteMany();
  await prisma.knowledgeContentHistory.deleteMany();
  await prisma.knowledgeContentAttachment.deleteMany();
  await prisma.knowledgeContentLink.deleteMany();
  await prisma.knowledgeContentPayrollTopicLink.deleteMany();
  await prisma.knowledgeContentTaskLink.deleteMany();
  await prisma.knowledgeContentArea.deleteMany();
  await prisma.knowledgeContent.deleteMany();
  await prisma.knowledgeArea.deleteMany({where:{parentId:{not:null}}});
  await prisma.knowledgeArea.deleteMany();
  await prisma.payrollReconciliationTopicHistory.deleteMany();
  await prisma.payrollReconciliationTopic.deleteMany();
  await prisma.standardTaskKnowledgeAttachment.deleteMany();
  await prisma.standardTaskKnowledgeHistory.deleteMany();
  await prisma.standardTaskKnowledgeLink.deleteMany();
  await prisma.standardTaskKnowledge.deleteMany();
  await prisma.standardTask.deleteMany();
  await prisma.taskCategory.deleteMany();
  await prisma.session.deleteMany();
  await prisma.userRole.deleteMany();
  await prisma.user.deleteMany();
}
beforeEach(async()=>{await clean();const users=await Promise.all([
  ["campus2.manager","Künstliche Campus-Verwaltung","ORDO_CAMPUS_VERWALTEN"],["campus2.reader","Künstliche Bearbeitung","MITARBEITER"],["campus2.reviewer","Künstliche Prüfung","PRUEFER"],["campus2.admin","Künstliche Administration","ADMINISTRATOR"],["campus2.payroll","Künstliche Lohnbearbeitung","LOHNSACHBEARBEITER"],
].map(async([username,fullName,role])=>prisma.user.create({data:{username,fullName,passwordHash:"test",active:true,mustChangePassword:false,roles:{create:{role}}}})));const auth=(index:number,role:string):AuthUser=>({id:users[index].id,username:users[index].username,fullName:users[index].fullName,active:true,mustChangePassword:false,roles:[role] as AuthUser["roles"]});manager=auth(0,"ORDO_CAMPUS_VERWALTEN");reader=auth(1,"MITARBEITER");reviewer=auth(2,"PRUEFER");admin=auth(3,"ADMINISTRATOR");payroll=auth(4,"LOHNSACHBEARBEITER");const category=await prisma.taskCategory.create({data:{name:"Künstliches Campus-2-Gebiet"}});const taskBase={active:true,categoryId:category.id,mandatory:false,rhythm:"Monatlich",legalFormGroups:"Alle",profitDeterminationMethods:"Alle",cashCondition:"Alle",payrollCondition:"Alle",fixedAssetsCondition:"Alle",receivablesPayablesCondition:"Alle",loansCondition:"Alle",vatCondition:"Alle",permanentExtensionCondition:"Alle",professionalVersion:"TEST"};const tasks=await Promise.all([prisma.standardTask.create({data:{...taskBase,taskId:"CAMPUS2-MON-001",title:"Künstliche Monatsaufgabe",checklistType:"Monat"}}),prisma.standardTask.create({data:{...taskBase,taskId:"CAMPUS2-JA-001",title:"Künstliche Jahresaufgabe",checklistType:"Jahresabschluss"}})]);taskIds=tasks.map(task=>task.id);const topic=await prisma.payrollReconciliationTopic.create({data:{key:"CAMPUS2-THEMA",title:"Künstliches Lohnthema",reviewQuestion:"Künstliche Prüffrage?",validFrom:new Date("2026-01-01"),topicType:"Einzelthema",requiredStandardFields:"[]",requiredDocumentTypes:"[]",createdByUserId:manager.id}});topicId=topic.id;const root=await saveKnowledgeArea(null,{key:"TEST_WISSEN",title:"Künstliches Testwissen",shortDescription:"Künstliches Hauptgebiet.",description:null,icon:null,sortOrder:1,parentId:null,status:"Aktiv"},manager);const second=await saveKnowledgeArea(null,{key:"TEST_STANDARD",title:"Künstliche Standards",shortDescription:"Künstliches zweites Gebiet.",description:null,icon:null,sortOrder:2,parentId:null,status:"Aktiv"},manager);areaIds=[root.id,second.id]});
afterAll(async()=>{await clean();await prisma.$disconnect()});
const input=()=>({key:"TEST-INHALT",title:"Künstlicher eigenständiger Wissensinhalt",shortDescription:"Künstliche Kurzbeschreibung",objective:"Künstliches Ziel",mainContent:"Künstliches Fachwissen",workingGuidance:"1. Künstlichen Schritt ausführen",firmStandard:"**Verbindlicher künstlicher Standard**",typicalErrors:"- Künstlicher Fehler",reviewerGuidance:"Nur künstlicher Prüferhinweis",internalHints:"Künstlicher interner Hinweis",status:"Aktiv" as const,contentTypes:["Kanzleistandard","Arbeitsanleitung"],targetAudiences:["ALLE","PRUEFER"],responsibleUserId:manager.id,areaIds,primaryAreaId:areaIds[0],taskLinks:taskIds.map((standardTaskId,index)=>({standardTaskId,linkType:index?"Ergänzendes Wissen":"Hauptanleitung",sortOrder:index*10,mainContent:index===0,contextHint:index?null:"Künstlicher Kontexthinweis"})),payrollTopicLinks:[{payrollReconciliationTopicId:topicId,linkType:"Hauptanleitung",sortOrder:0,mainContent:true,contextHint:null}],tags:["Künstlich","Testwissen"],nextReviewDate:null,majorUpdate:true});
describe("Ordo Campus 2.0",()=>{
  it("verwaltet Haupt- und Untergebiete mit maximal einer Hierarchieebene",async()=>{const child=await saveKnowledgeArea(null,{key:"TEST_UNTER",title:"Künstliches Untergebiet",shortDescription:"Künstliche Untergliederung.",description:null,icon:null,sortOrder:3,parentId:areaIds[0],status:"Aktiv"},manager);await expect(saveKnowledgeArea(null,{key:"TEST_ZU_TIEF",title:"Künstlich zu tief",shortDescription:"Nicht zulässige Tiefe.",description:null,icon:null,sortOrder:4,parentId:child.id,status:"Aktiv"},manager)).rejects.toBeInstanceOf(KnowledgePlatformError);await saveKnowledgeArea(child.id,{key:"TEST_UNTER",title:"Künstliches Untergebiet geändert",shortDescription:"Künstliche Untergliederung.",description:null,icon:null,sortOrder:3,parentId:areaIds[0],status:"Archiviert"},manager);expect((await prisma.knowledgeArea.findUniqueOrThrow({where:{id:child.id}})).status).toBe("Archiviert")});
  it("speichert Mehrfachgebiete mit genau einem primären Gebiet",async()=>{const content=await saveKnowledgeContent(null,input(),manager);const areas=await prisma.knowledgeContentArea.findMany({where:{knowledgeContentId:content.id}});expect(areas).toHaveLength(2);expect(areas.filter(area=>area.primaryArea)).toHaveLength(1)});
  it("verknüpft mehrere Aufgaben und ein Lohnthema ohne Wissensduplikat",async()=>{const content=await saveKnowledgeContent(null,input(),manager);expect(await prisma.knowledgeContentTaskLink.count({where:{knowledgeContentId:content.id}})).toBe(2);expect(await prisma.knowledgeContentPayrollTopicLink.count({where:{knowledgeContentId:content.id}})).toBe(1);expect(await prisma.knowledgeContent.count()).toBe(1)});
  it("entfernt Verknüpfungen ohne den Wissensinhalt zu löschen",async()=>{const content=await saveKnowledgeContent(null,input(),manager);await saveKnowledgeContent(content.id,{...input(),taskLinks:[],payrollTopicLinks:[]},manager);expect(await prisma.knowledgeContent.count({where:{id:content.id}})).toBe(1);expect(await prisma.knowledgeContentTaskLink.count({where:{knowledgeContentId:content.id}})).toBe(0)});
  it("schützt jede Pflege vor normalen Benutzern und reinen Administratoren",async()=>{await expect(saveKnowledgeContent(null,input(),reader)).rejects.toMatchObject({code:"NOT_ALLOWED"});await expect(saveKnowledgeContent(null,input(),admin)).rejects.toMatchObject({code:"NOT_ALLOWED"});expect(canManageOrdoCampus(admin)).toBe(false)});
  it("lässt Lohnbenutzer aktive Inhalte kanzleiweit lesen, ohne Rechnungswesenrechte zu verleihen",async()=>{const content=await saveKnowledgeContent(null,{...input(),targetAudiences:["PRUEFER"]},manager);await recordKnowledgeView(content.id,payroll);expect(await prisma.knowledgeUserProgress.count({where:{userId:payroll.id}})).toBe(1);expect(payroll.roles).toEqual(["LOHNSACHBEARBEITER"])});
  it("schützt Prüferhinweise rollenabhängig",()=>{expect(canReadCampusReviewerGuidance(reader)).toBe(false);expect(canReadCampusReviewerGuidance(reviewer)).toBe(true)});
  it("aktualisiert zuletzt angesehen pro Benutzer ohne fremde Historie",async()=>{const content=await saveKnowledgeContent(null,input(),manager);await recordKnowledgeView(content.id,reader);await recordKnowledgeView(content.id,reader);const progress=await prisma.knowledgeUserProgress.findUniqueOrThrow({where:{userId_knowledgeContentId:{userId:reader.id,knowledgeContentId:content.id}}});expect(progress.viewCount).toBe(2);expect(await prisma.knowledgeUserProgress.count({where:{userId:reviewer.id}})).toBe(0)});
  it("markiert freiwillig als gelesen und entfernt die Markierung wieder",async()=>{const content=await saveKnowledgeContent(null,input(),manager);await setKnowledgeRead(content.id,true,reader);expect((await prisma.knowledgeUserProgress.findFirstOrThrow({where:{userId:reader.id}})).readAt).not.toBeNull();await setKnowledgeRead(content.id,false,reader);expect((await prisma.knowledgeUserProgress.findFirstOrThrow({where:{userId:reader.id}})).readAt).toBeNull()});
  it("archiviert Inhalte ohne Aufgaben, Themen oder Verlauf zu löschen",async()=>{const content=await saveKnowledgeContent(null,input(),manager);await archiveKnowledgeContent(content.id,manager);const archived=await prisma.knowledgeContent.findUniqueOrThrow({where:{id:content.id},include:{taskLinks:true,payrollTopicLinks:true,history:true}});expect(archived.status).toBe("Archiviert");expect(archived.taskLinks).toHaveLength(2);expect(archived.payrollTopicLinks).toHaveLength(1);expect(archived.history.some(entry=>entry.changedArea==="Status")).toBe(true)});
  it("normalisiert Schlagwörter und verhindert Dubletten",async()=>{const value=input();value.tags=["Künstlich","künstlich","Testwissen"];const content=await saveKnowledgeContent(null,value,manager);expect(await prisma.knowledgeContentTag.count({where:{knowledgeContentId:content.id}})).toBe(2)});
  it("erhält Veröffentlichungsdatum und vollständige Verknüpfungsmetadaten bei normaler Bearbeitung",async()=>{const content=await saveKnowledgeContent(null,input(),manager);const before=await prisma.knowledgeContent.findUniqueOrThrow({where:{id:content.id}});const changed=input();changed.title="Künstlicher eigenständiger Wissensinhalt geändert";await saveKnowledgeContent(content.id,changed,manager);const after=await prisma.knowledgeContent.findUniqueOrThrow({where:{id:content.id},include:{taskLinks:true}});expect(after.publishedAt?.getTime()).toBe(before.publishedAt?.getTime());expect(after.taskLinks.find(link=>link.mainContent)).toMatchObject({linkType:"Hauptanleitung",sortOrder:0,contextHint:"Künstlicher Kontexthinweis"})});
  it("erlaubt für Wissenslinks nur interne sowie HTTP- oder HTTPS-Adressen",()=>{expect(knowledgeContentLinkSchema.safeParse({title:"Künstlich",url:"javascript:alert(1)",linkType:"Fachquelle",description:"",sortOrder:0,active:true}).success).toBe(false);expect(knowledgeContentLinkSchema.safeParse({title:"Künstlich",url:"https://example.invalid/wissen",linkType:"Fachquelle",description:"",sortOrder:0,active:true}).success).toBe(true)});
  it("überführt Legacy-Wissen, Links, Verlauf, Aufgabe und Thema idempotent",async()=>{const legacy=await prisma.standardTaskKnowledge.create({data:{standardTaskId:taskIds[0],status:"Aktiv",shortDescription:"Künstliches Legacy-Wissen",links:{create:{title:"Künstlicher Link",url:"https://example.invalid/campus2",linkType:"Externe Fachquelle"}}}});await prisma.standardTaskKnowledgeHistory.create({data:{knowledgeId:legacy.id,standardTaskId:taskIds[0],actorUserId:manager.id,actorNameSnapshot:manager.fullName,changedArea:"Wissen",description:"Künstlich angelegt."}});await prisma.payrollReconciliationTopic.update({where:{id:topicId},data:{campusStandardTaskId:taskIds[0]}});await provisionKnowledgePlatformFromLegacy(prisma,manager.id);const first={contents:await prisma.knowledgeContent.count({where:{legacyKnowledgeId:legacy.id}}),links:await prisma.knowledgeContentLink.count(),history:await prisma.knowledgeContentHistory.count(),tasks:await prisma.knowledgeContentTaskLink.count(),topics:await prisma.knowledgeContentPayrollTopicLink.count()};await provisionKnowledgePlatformFromLegacy(prisma,manager.id);expect({contents:await prisma.knowledgeContent.count({where:{legacyKnowledgeId:legacy.id}}),links:await prisma.knowledgeContentLink.count(),history:await prisma.knowledgeContentHistory.count(),tasks:await prisma.knowledgeContentTaskLink.count(),topics:await prisma.knowledgeContentPayrollTopicLink.count()}).toEqual(first);expect(first.contents).toBe(1);expect(first.links).toBe(1)});
});
