import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { KnowledgeForm } from "../knowledge-form";
import { archiveKnowledgeContentAction, copyKnowledgeContentAction, createKnowledgeLinkAction, updateKnowledgeAttachmentAction, updateKnowledgeLinkAction, uploadKnowledgeAttachmentAction } from "../../actions";
import { formData } from "../neu/page";
import { requireUser } from "@/lib/auth";
import { canManageOrdoCampus } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { formatDateTime } from "@/lib/format";
import { CAMPUS_ATTACHMENT_ACCEPT, CAMPUS_ATTACHMENT_MAX_BYTES, formatCampusFileSize } from "@/lib/ordo-campus-attachment-service";

export default async function EditKnowledgeContentPage({params}:{params:Promise<{id:string}>}) {
  const user=await requireUser(); if(!canManageOrdoCampus(user))redirect("/zugriff-verweigert?bereich=Wissensmanagement"); const id=Number((await params).id);
  const [content,data]=await Promise.all([prisma.knowledgeContent.findUnique({where:{id},include:{areas:true,taskLinks:true,payrollTopicLinks:true,tags:{include:{knowledgeTag:true}},history:{orderBy:{occurredAt:"desc"},take:100},links:{orderBy:{sortOrder:"asc"}},attachments:{orderBy:{sortOrder:"asc"}}}}),formData()]); if(!content)notFound();
  return <div><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><Link className="text-sm font-semibold text-[var(--color-primary-dark)] hover:underline" href="/verwaltung/wissensmanagement">← Wissensinhalte</Link><h1 className="mt-3 text-3xl font-bold">{content.title}</h1><p className="mt-1 text-sm text-[var(--color-text-muted)]">Pflege ausschließlich im Wissensmanagement; alle Anwendungsorte verwenden denselben aktiven Inhalt.</p></div><div className="flex gap-2"><Link className="button-secondary" href={`/ordo-campus/wissen/${content.id}`}>Leseansicht</Link><form action={copyKnowledgeContentAction}><input type="hidden" name="id" value={content.id}/><button className="button-secondary">Kopieren</button></form>{content.status!=="Archiviert"&&<form action={archiveKnowledgeContentAction}><input type="hidden" name="id" value={content.id}/><button className="button-secondary">Archivieren</button></form>}</div></header>
    <KnowledgeForm content={content} {...data}/>
    <section className="mt-7 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Links verwalten</h2><div className="mt-4 space-y-3">{content.links.map(link=><form action={updateKnowledgeLinkAction} className="grid gap-3 rounded border bg-[var(--color-background)] p-4 md:grid-cols-2 xl:grid-cols-6" key={link.id}><input type="hidden" name="linkId" value={link.id}/><Field label="Titel"><input className="input" name="title" defaultValue={link.title} required/></Field><Field label="URL"><input className="input" name="url" defaultValue={link.url} required/></Field><Field label="Typ"><input className="input" name="linkType" defaultValue={link.linkType} required/></Field><Field label="Beschreibung"><input className="input" name="description" defaultValue={link.description??""}/></Field><Field label="Sortierung"><input className="input" type="number" name="sortOrder" defaultValue={link.sortOrder}/></Field><div className="flex items-end gap-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="active" value="1" defaultChecked={link.active}/>Aktiv</label><button className="button-secondary">Speichern</button></div></form>)}</div><form action={createKnowledgeLinkAction} className="mt-4 grid gap-3 rounded border border-dashed p-4 md:grid-cols-2 xl:grid-cols-6"><input type="hidden" name="id" value={content.id}/><Field label="Titel"><input className="input" name="linkTitle" required/></Field><Field label="URL"><input className="input" name="linkUrl" placeholder="https://…" required/></Field><Field label="Typ"><input className="input" name="linkType" defaultValue="Externe Fachquelle" required/></Field><Field label="Beschreibung"><input className="input" name="linkDescription"/></Field><Field label="Sortierung"><input className="input" name="linkSortOrder" type="number" defaultValue="0"/></Field><button className="button-primary self-end">Link ergänzen</button></form></section>
    <section className="mt-7 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Geschützte Anhänge</h2><p className="mt-2 text-sm text-[var(--color-text-muted)]">PDF, DOCX, XLSX, PNG und JPG bis {CAMPUS_ATTACHMENT_MAX_BYTES/1024/1024} MB. Speicherung ausschließlich unter storage/ordo-campus; keine echten Mandanten- oder Personendaten.</p><form action={uploadKnowledgeAttachmentAction} className="mt-4 grid gap-3 rounded border border-dashed p-4 md:grid-cols-2 xl:grid-cols-5"><input type="hidden" name="id" value={content.id}/><Field label="Datei"><input className="input" type="file" name="file" accept={CAMPUS_ATTACHMENT_ACCEPT} required/></Field><Field label="Anzeigename"><input className="input" name="displayName" required/></Field><Field label="Beschreibung"><input className="input" name="description"/></Field><Field label="Sortierung"><input className="input" type="number" name="sortOrder" defaultValue="0"/></Field><button className="button-primary self-end">Anhang hochladen</button></form><div className="mt-4 space-y-3">{content.attachments.map(file=><form action={updateKnowledgeAttachmentAction} className="grid gap-3 rounded bg-[var(--color-background)] p-4 md:grid-cols-2 xl:grid-cols-5" key={file.id}><input type="hidden" name="attachmentId" value={file.id}/><Field label="Anzeigename"><input className="input" name="displayName" defaultValue={file.displayName} required/></Field><Field label="Beschreibung"><input className="input" name="description" defaultValue={file.description??""}/></Field><Field label="Sortierung"><input className="input" type="number" name="sortOrder" defaultValue={file.sortOrder}/></Field><div className="text-sm"><strong>{file.fileExtension} · {formatCampusFileSize(file.fileSizeBytes)}</strong><p>{file.status}</p></div><div className="flex items-end gap-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="active" value="1" defaultChecked={file.status==="Aktiv"}/>Aktiv</label><a className="button-secondary" href={`/api/ordo-campus/attachments/${file.id}/download?pflege=1`}>Download</a><button className="button-secondary">Speichern</button></div></form>)}</div></section>
    <section className="mt-7 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Verlauf</h2><ol className="mt-3 space-y-3">{content.history.map(entry=><li className="border-l-2 border-[var(--color-primary)] pl-3 text-sm" key={entry.id}><strong>{entry.changedArea}</strong><p>{entry.description}</p><span className="text-xs text-[var(--color-text-muted)]">{formatDateTime(entry.occurredAt)} · {entry.actorNameSnapshot}</span></li>)}</ol></section>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs font-semibold">{label}{children}</label>}
