import Link from "next/link";
import { redirect } from "next/navigation";
import { saveKnowledgeAreaAction } from "../actions";
import { requireUser } from "@/lib/auth";
import { canManageOrdoCampus } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";

export default async function ManageKnowledgeAreasPage() { const user=await requireUser(); if(!canManageOrdoCampus(user))redirect("/zugriff-verweigert?bereich=Wissensmanagement"); const areas=await prisma.knowledgeArea.findMany({include:{parent:true,_count:{select:{contentLinks:true,children:true}}},orderBy:[{sortOrder:"asc"},{title:"asc"}]}); const roots=areas.filter(area=>!area.parentId); return <div><header className="mb-6"><Link className="text-sm font-semibold text-[var(--color-primary-dark)] hover:underline" href="/verwaltung?bereich=wissensmanagement">← Wissensmanagement</Link><h1 className="mt-3 text-3xl font-bold">Wissensgebiete verwalten</h1></header><AreaForm roots={roots}/><div className="mt-6 space-y-3">{areas.map(area=><details className="rounded-xl border bg-white p-5" key={area.id}><summary className="cursor-pointer font-bold">{area.parentId?"↳ ":""}{area.title} <span className="ml-2 text-xs font-normal text-[var(--color-text-muted)]">{area.status} · {area._count.contentLinks} Inhalte</span></summary><div className="mt-5"><AreaForm area={area} roots={roots}/><p className="mt-3 text-xs text-[var(--color-text-muted)]">Gebiete mit Inhalten werden nicht gelöscht; die Archivierung erhält sämtliche Zuordnungen.</p></div></details>)}</div></div>; }
function AreaForm({area,roots}:{area?:{id:number;key:string;title:string;shortDescription:string;description:string|null;icon:string|null;sortOrder:number;status:string;parentId:number|null};roots:{id:number;title:string}[]}) { return <form action={saveKnowledgeAreaAction} className="grid gap-3 rounded-xl border border-[var(--color-border)] bg-[var(--color-background)] p-4 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="id" value={area?.id??""}/><Field label="Schlüssel" name="key" value={area?.key} required/><Field label="Bezeichnung" name="title" value={area?.title} required/><Field label="Kurzbeschreibung" name="shortDescription" value={area?.shortDescription} required/><Field label="Symbol" name="icon" value={area?.icon}/><Field label="Sortierung" name="sortOrder" value={String(area?.sortOrder??0)} type="number"/><label className="grid gap-1 text-xs font-semibold">Übergeordnetes Gebiet<select className="input" name="parentId" defaultValue={area?.parentId??""}><option value="">Hauptgebiet</option>{roots.filter(root=>root.id!==area?.id).map(root=><option value={root.id} key={root.id}>{root.title}</option>)}</select></label><label className="grid gap-1 text-xs font-semibold">Status<select className="input" name="status" defaultValue={area?.status??"Aktiv"}><option>Aktiv</option><option>Archiviert</option></select></label><label className="grid gap-1 text-xs font-semibold xl:col-span-3">Beschreibung<textarea className="input" name="description" defaultValue={area?.description??""}/></label><button className="button-primary self-end">{area?"Gebiet speichern":"Gebiet anlegen"}</button></form>; }
function Field({label,name,value,type="text",required=false}:{label:string;name:string;value?:string|null;type?:string;required?:boolean}) { return <label className="grid gap-1 text-xs font-semibold">{label}<input className="input" name={name} type={type} defaultValue={value??""} required={required}/></label>; }
