import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { annualProgress,ANNUAL_REVIEW_STATUSES,ANNUAL_TASK_STATUSES,type AnnualAction } from "@/lib/annual-checklist-service";
import { canManageCustomAnnualTasks,canProcessAnnualChecklist,canReleaseAnnualChecklist,canReviewAnnualChecklist,canViewAnnualChecklist } from "@/lib/permissions";
import { formatDate,formatDateTime } from "@/lib/format";
import { ToastMessage } from "@/app/components/toast-message";
import { completeAnnualReworkAction,createCustomAnnualTaskAction,createFromMonthlyAction,reopenAnnualAction,reviewAnnualTaskAction,saveAnnualTaskChangesAction,transitionAnnualAction } from "../actions";
import { OrdoCampusPanel } from "@/app/components/ordo-campus-panel";
import { TaskProcessingForm } from "@/app/components/task-processing-form";
import { ChecklistBatchProvider } from "@/app/components/checklist-batch-provider";
import { ChecklistWorkspaceTools, type ChecklistNavigatorTask } from "@/app/components/checklist-workspace-tools";

const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";
export default async function AnnualDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const user=await requireUser(),id=Number((await params).id),query=await searchParams;
 const checklist=await prisma.annualChecklist.findUnique({where:{id},include:{client:true,tasks:{include:{standardTask:{select:{campusKnowledge:{select:{status:true}}}}},orderBy:[{categorySortOrder:"asc"},{sortOrderSnapshot:"asc"},{taskIdSnapshot:"asc"}]},history:{include:{annualChecklistTask:{select:{taskIdSnapshot:true}}},orderBy:{occurredAt:"desc"}}}});
 if(!checklist)notFound();if(!canViewAnnualChecklist(user,checklist))redirect("/zugriff-verweigert?bereich=Jahresabschluss");
 const monthly=await prisma.accountingPeriod.findMany({where:{clientId:checklist.clientId,calendarYear:checklist.fiscalYear,checklistType:"Monat"},include:{tasks:true},orderBy:{month:"asc"}});
 const openMonthlyPoints=monthly.flatMap(period=>period.tasks.filter(task=>["Offen","In Bearbeitung","In Folgemonat übertragen"].includes(task.status)||["Rückfrage","Beanstandung"].includes(task.reviewStatus)).map(task=>({...task,period})));
 const monthlySummary={total:monthly.length,completed:monthly.filter(p=>p.processingStatus==="Abgeschlossen").length,open:monthly.filter(p=>p.processingStatus!=="Abgeschlossen").length,mandatory:monthly.flatMap(p=>p.tasks).filter(t=>t.mandatorySnapshot&&!["Erledigt","Nicht zutreffend","In Folgemonat übertragen"].includes(t.status)).length,transferred:monthly.flatMap(p=>p.tasks).filter(t=>t.status==="In Folgemonat übertragen").length,review:monthly.flatMap(p=>p.tasks).filter(t=>["Rückfrage","Beanstandung"].includes(t.reviewStatus)).length};
 const progress=annualProgress(checklist.tasks),process=canProcessAnnualChecklist(user,checklist),review=canReviewAnnualChecklist(user,checklist),release=canReleaseAnnualChecklist(user,checklist),locked=["Fachlich abgeschlossen","Zur Freigabe","Freigegeben"].includes(checklist.status);
 const groups=Map.groupBy(checklist.tasks,task=>task.categorySnapshot);
 const navigatorTasks:ChecklistNavigatorTask[]=checklist.tasks.map(task=>({id:task.id,code:task.taskIdSnapshot,title:task.titleSnapshot,category:task.categorySnapshot,status:task.status,reviewStatus:task.reviewStatus,hasQuestion:["Rückfrage","Beanstandung"].includes(task.reviewStatus),transferred:Boolean(task.sourceMonthlyTaskId),campusAvailable:task.standardTask?.campusKnowledge?.status==="Aktiv"}));
 return <ChecklistBatchProvider saveAction={saveAnnualTaskChangesAction.bind(null,id)} totalTasks={progress.total} serverCompletedTasks={progress.completed}><div id="workflow" tabIndex={-1}><Link className="text-sm font-semibold text-[var(--color-primary-dark)] hover:underline" href="/jahresabschluesse">← Zur Jahresabschlussübersicht</Link><ToastMessage message={one(query.fehler)||(one(query.erfolg)?"Die Aktion wurde erfolgreich gespeichert.":"")} type={one(query.fehler)?"error":"success"}/>
 <header id="checklist-full-header" tabIndex={-1} className="my-6"><p className="text-sm font-semibold uppercase text-[var(--color-primary)]">Mandant {checklist.client.clientNumber}</p><h1 className="mt-2 text-3xl font-bold">{checklist.client.name} · Jahresabschluss {checklist.fiscalYear}</h1></header>
 <section className="rounded-lg border bg-white p-5"><dl className="grid gap-4 md:grid-cols-3 xl:grid-cols-6"><Data label="Status" value={checklist.status}/><Data label="Abschlussstichtag" value={formatDate(checklist.closingDate)}/><Data label="Bearbeiter" value={checklist.processorNameSnapshot}/><Data label="Prüfer" value={checklist.reviewerNameSnapshot}/><Data label="Kanzleileitung" value={checklist.managementNameSnapshot}/><Data label="Fortschritt" value={`${progress.completed}/${progress.total} · ${progress.percent} %`}/><Data label="Offene Pflicht" value={String(progress.mandatoryOpen)}/><Data label="Offene Prüfpunkte" value={String(progress.openReviewPoints)}/><Data label="Rechtsform" value={checklist.legalFormSnapshot}/><Data label="Gewinnermittlung" value={checklist.profitDeterminationSnapshot}/></dl><div className="mt-5 border-t pt-4"><WorkflowActions id={id} status={checklist.status} process={process} review={review} release={release} person={user.fullName} openReview={progress.openReviewPoints}/></div></section>
 <ChecklistWorkspaceTools label={`Jahresabschluss ${checklist.fiscalYear}`} tasks={navigatorTasks} statusDetails={[["Nicht zutreffend",String(checklist.tasks.filter(task=>task.status==="Nicht zutreffend").length)],["In Bearbeitung",String(checklist.tasks.filter(task=>task.status==="In Bearbeitung").length)],["Offene Pflicht",String(progress.mandatoryOpen)],["Beanstandet / Rückfrage",String(progress.openReviewPoints)],["Checklistenstatus",checklist.status]]}/>
 {monthlySummary.open>0&&<div className="mt-5 rounded border border-amber-300 bg-amber-50 p-4 text-sm font-semibold">{monthlySummary.open} Monatschecklisten des Wirtschaftsjahres sind noch nicht abgeschlossen. Die Jahresabschlussbearbeitung darf parallel fortgeführt werden.</div>}
 <section className="mt-7"><h2 className="text-xl font-semibold">Monatschecklisten des Wirtschaftsjahres</h2><div className="mt-3 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{Object.entries({Monate:monthlySummary.total,Abgeschlossen:monthlySummary.completed,Offen:monthlySummary.open,"Offene Pflicht":monthlySummary.mandatory,Überträge:monthlySummary.transferred,"Offene Prüfpunkte":monthlySummary.review}).map(([label,value])=><div className="rounded border bg-white p-3" key={label}><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>)}</div><div className="mt-3 flex flex-wrap gap-2">{monthly.map(period=><Link className="button-secondary" href={`/monatschecklisten/${period.id}`} key={period.id}>{period.periodLabel} · {period.processingStatus}</Link>)}</div></section>
 <section className="mt-7"><h2 className="text-xl font-semibold">Offene Punkte aus dem laufenden Rechnungswesen</h2><p className="mt-1 text-sm text-slate-600">Hinweise werden nicht automatisch dupliziert. Prüfer oder Kanzleileitung können kontrolliert eine eigenständige Jahresabschlussaufgabe anlegen.</p><div className="mt-3 overflow-x-auto rounded border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Monat","Aufgabe","Bearbeitung","Prüfung","Notiz","Aktion"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{openMonthlyPoints.map(task=><tr className="border-t" key={task.id}><td className="p-3"><Link className="font-semibold text-[var(--color-primary-dark)]" href={`/monatschecklisten/${task.periodId}#aufgabe-${task.id}`}>{task.period.periodLabel}</Link></td><td className="p-3">{task.titleSnapshot}</td><td className="p-3">{task.status}</td><td className="p-3">{task.reviewStatus}</td><td className="p-3">{task.processingNote??task.reviewNote??"–"}</td><td className="p-3">{(review||release)&&!checklist.tasks.some(t=>t.sourceMonthlyTaskId===task.id)?<form action={createFromMonthlyAction.bind(null,id,task.id)} data-workflow-action="true"><button className="button-secondary">Als Aufgabe übernehmen</button></form>:"–"}</td></tr>)}{!openMonthlyPoints.length&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Keine offenen Punkte aus Monatschecklisten.</td></tr>}</tbody></table></div></section>
 <section className="mt-7"><h2 className="text-xl font-semibold">Jahresabschlussaufgaben</h2><div className="mt-4 space-y-6">{[...groups].map(([category,tasks])=><div key={category}><h3 className="mb-2 text-lg font-semibold">{category}</h3><div className="space-y-3">{tasks.map(task=><article id={`aufgabe-${task.id}`} tabIndex={-1} className={`rounded border bg-white p-4 focus:outline-none focus:ring-2 focus:ring-[var(--color-focus)] ${["Rückfrage","Beanstandung"].includes(task.reviewStatus)?"border-amber-400":""}`} key={task.id}><div className="grid gap-3 xl:grid-cols-[10rem_1fr_10rem_10rem]"><div><div className="font-mono text-xs font-semibold">{task.taskIdSnapshot}</div><div className="text-xs text-slate-500">{task.origin}</div></div><div><h4 className="font-semibold">{task.titleSnapshot}{task.mandatorySnapshot&&<span className="ml-2 rounded bg-red-100 px-2 py-0.5 text-xs">Pflicht</span>}</h4>{task.workInstructionSnapshot&&<p className="mt-1 text-sm text-slate-600">{task.workInstructionSnapshot}</p>}<OrdoCampusPanel kind="jahresabschluss" taskId={task.id} activeKnowledge={task.standardTask?.campusKnowledge?.status==="Aktiv"}/></div><Data label="Bearbeitung" value={task.status}/><Data label="Prüfung" value={task.reviewStatus}/></div>{task.reviewNote&&<p className="mt-3 rounded bg-amber-50 p-3 text-sm"><b>Prüfnotiz:</b> {task.reviewNote}</p>}{task.sourceMonthLabel&&<p className="mt-3 text-sm"><b>Herkunft:</b> {task.sourceMonthLabel} · {task.sourceNoteSnapshot??"ohne Notiz"}</p>}<TaskForms task={task} checklistId={id} status={checklist.status} process={process} review={review} locked={locked}/></article>)}</div></div>)}</div></section>
 {canManageCustomAnnualTasks(user)&&(review||release)&&<details className="mt-7 rounded border bg-white p-5"><summary className="cursor-pointer font-semibold">Mandantenspezifische Jahresabschlussvorlage anlegen</summary><form action={createCustomAnnualTaskAction.bind(null,id,checklist.clientId)} data-workflow-action="true" className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Titel"><input className="input" name="title" required/></Field><Field label="Kategorie"><input className="input" name="category" defaultValue="Abschlussvorbereitung" required/></Field><Field label="Beschreibung"><textarea className="input" name="description"/></Field><Field label="Gültig ab Wirtschaftsjahr"><input className="input" type="number" name="validFromYear" defaultValue={checklist.fiscalYear}/></Field><Field label="Gültig bis"><input className="input" type="number" name="validUntilYear"/></Field><Field label="Sortierung"><input className="input" type="number" name="sortOrder" defaultValue="0"/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="mandatory"/> Pflichtaufgabe</label><button className="button-primary">Vorlage anlegen</button></form></details>}
 {checklist.status==="Freigegeben"&&release&&<section className="mt-7 rounded border-2 border-red-300 bg-red-50 p-5"><h2 className="text-xl font-semibold">Freigabe wieder öffnen</h2><form action={reopenAnnualAction.bind(null,id)} data-workflow-action="true" className="mt-3 flex flex-wrap items-end gap-3"><Field label="Verpflichtende Begründung"><input className="input min-w-80" name="reason" required/></Field><button className="button-primary">Begründet wieder öffnen</button></form></section>}
 <section className="mt-8"><h2 className="text-xl font-semibold">Fachlicher Verlauf</h2><div className="mt-3 overflow-x-auto rounded border bg-white"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-[var(--color-primary-light)]"><tr>{["Zeitpunkt","Ereignis","Person","Rolle","Aufgabe","Beschreibung","Vorher","Neu","Begründung"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{checklist.history.map(entry=><tr className="border-t" key={entry.id}><td className="p-3">{formatDateTime(entry.occurredAt)}</td><td className="p-3 font-semibold">{entry.eventType}</td><td className="p-3">{entry.actorNameSnapshot}</td><td className="p-3">{entry.actorRoleSnapshot}</td><td className="p-3">{entry.annualChecklistTask?.taskIdSnapshot??"–"}</td><td className="p-3">{entry.description}</td><td className="p-3">{entry.previousValue??"–"}</td><td className="p-3">{entry.newValue??"–"}</td><td className="p-3">{entry.reason??"–"}</td></tr>)}</tbody></table></div></section></div></ChecklistBatchProvider>
}

function WorkflowActions({id,status,process,review,release,person,openReview}:{id:number;status:string;process:boolean;review:boolean;release:boolean;person:string;openReview:number}){
 let action:AnnualAction|undefined,label="";
 if(status==="Offen"&&process){action="BEGIN";label="Vorbereitung beginnen"}else if(["In Vorbereitung","Nachbearbeitung"].includes(status)&&process){action="SUBMIT_REVIEW";label=status==="Nachbearbeitung"?"Erneut zur Prüfung übergeben":"Zur Prüfung übergeben"}else if(status==="Zur Prüfung"&&review){action="BEGIN_REVIEW";label="Prüfung beginnen"}else if(status==="In Prüfung"&&review){action=openReview?"RETURN_REWORK":"PROFESSIONAL_COMPLETE";label=openReview?"Zur Nachbearbeitung zurückgeben":"Fachlich abschließen"}else if(status==="Fachlich abgeschlossen"&&review){action="SUBMIT_RELEASE";label="Zur Freigabe übergeben"}else if(status==="Zur Freigabe"&&release){action="RELEASE";label="Endgültig freigeben"}
 if(!action)return <p className="text-sm text-slate-600">Für Ihre Rolle ist im aktuellen Status keine Hauptaktion verfügbar.</p>;
 return <form action={transitionAnnualAction.bind(null,id,action)} data-workflow-action="true" className="flex flex-wrap items-end gap-3"><div className="rounded bg-[var(--color-primary-light)] px-3 py-2 text-sm">Diese Aktion wird ausgeführt von: <b>{person}</b></div>{action==="RELEASE"&&<Field label="Optionale Freigabenotiz"><input className="input" name="note"/></Field>}<button className="button-primary">{label}</button></form>
}
function TaskForms({task,checklistId,status,process,review,locked}:{task:Awaited<ReturnType<typeof prisma.annualChecklistTask.findFirstOrThrow>>;checklistId:number;status:string;process:boolean;review:boolean;locked:boolean}){
 return <div className="mt-4 grid gap-3 xl:grid-cols-2">{process&&!locked&&["Offen","In Vorbereitung","Nachbearbeitung"].includes(status)&&<TaskProcessingForm taskId={task.id} title={task.titleSnapshot} updatedAt={task.updatedAt.toISOString()} statuses={ANNUAL_TASK_STATUSES} initialStatus={task.status} processingNote={task.processingNote} notApplicableReason={task.notApplicableReason}/>} {review&&status==="In Prüfung"&&<form data-workflow-action="true" className="rounded border border-[var(--color-primary)] p-3" action={reviewAnnualTaskAction.bind(null,task.id,checklistId)}><Field label="Prüfstatus"><select className="input" name="reviewStatus" defaultValue={["Nicht geprüft","Erledigt nach Nachbearbeitung"].includes(task.reviewStatus)?"":task.reviewStatus} required><option value="">Bitte ausdrücklich auswählen</option>{ANNUAL_REVIEW_STATUSES.filter(v=>!["Nicht geprüft","Erledigt nach Nachbearbeitung","In Prüfung"].includes(v)).map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Prüfnotiz"><textarea className="input" name="reviewNote" defaultValue={task.reviewNote??""}/></Field><button className="button-primary mt-2">Prüfung speichern</button></form>}{process&&status==="Nachbearbeitung"&&["Rückfrage","Beanstandung"].includes(task.reviewStatus)&&<form data-workflow-action="true" className="rounded border border-amber-300 bg-amber-50 p-3" action={completeAnnualReworkAction.bind(null,task.id,checklistId)}><Field label="Antwort"><textarea className="input" name="response" required/></Field><button className="button-primary mt-2">Nachbearbeitung erledigt</button></form>}</div>
}
function Data({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
