import type { ClientVehicle } from "@prisma/client";

export function VehicleForm({action,vehicle,clients,clientId,itemId,returnTo}:{action:(formData:FormData)=>void|Promise<void>;vehicle?:ClientVehicle;clients?:Array<{id:number;clientNumber:string;name:string}>;clientId?:number;itemId?:number;returnTo?:string}){
  return <form action={action} className="space-y-5">
    {clients&&<Field label="Mandant"><select className="input" name="clientId" defaultValue={clientId??""} required><option value="">Bitte auswählen</option>{clients.map(client=><option key={client.id} value={client.id}>{client.clientNumber} · {client.name}</option>)}</select></Field>}
    {itemId&&<input type="hidden" name="reconciliationItemId" value={itemId}/>} {returnTo&&<input type="hidden" name="returnTo" value={returnTo}/>}
    <div className="grid gap-4 md:grid-cols-2"><Field label="Interne Fahrzeugreferenz"><input className="input" name="referenceNumber" defaultValue={vehicle?.referenceNumber??""}/></Field><Field label="Fahrzeugbezeichnung"><input className="input" name="description" defaultValue={vehicle?.description??""} required/></Field><Field label="Kennzeichen"><input className="input" name="licensePlate" defaultValue={vehicle?.licensePlate??""}/></Field><Field label="Nutzer"><input className="input" name="userName" defaultValue={vehicle?.userName??""} required/></Field><Field label="Funktion"><select className="input" name="userFunction" defaultValue={vehicle?.userFunction??"Arbeitnehmer"}>{["Geschäftsführer","Unternehmer","Arbeitnehmer","sonstige"].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Eigentum oder Leasing"><select className="input" name="ownershipType" defaultValue={vehicle?.ownershipType??"Leasing"}><option>Eigentum</option><option>Leasing</option></select></Field><Field label="Bruttolistenpreis in Euro"><input className="input" name="grossListPrice" type="number" step="0.01" defaultValue={vehicle?.grossListPriceCents?vehicle.grossListPriceCents/100:""}/></Field><Field label="Vertragsreferenz"><input className="input" name="contractReference" defaultValue={vehicle?.contractReference??""}/></Field><Field label="Vertragsdatum"><input className="input" name="contractDate" type="date" defaultValue={vehicle?.contractDate?.toISOString().slice(0,10)??""}/></Field><Field label="Dokumentenhinweis"><input className="input" name="documentReference" defaultValue={vehicle?.documentReference??""}/></Field><Field label="Gültig ab"><input className="input" name="validFrom" type="date" defaultValue={vehicle?.validFrom.toISOString().slice(0,10)??""} required/></Field><Field label="Gültig bis"><input className="input" name="validUntil" type="date" defaultValue={vehicle?.validUntil?.toISOString().slice(0,10)??""}/></Field><Field label="Rechnungswesenkonto"><input className="input" name="accountingAccount" defaultValue={vehicle?.accountingAccount??""}/></Field><Field label="Rechnungswesengrundlage"><input className="input" name="accountingBasis" defaultValue={vehicle?.accountingBasis??""}/></Field><Field label="Status"><select className="input" name="status" defaultValue={vehicle?.status??"Aktiv"}><option>Aktiv</option><option>Beendet</option><option>Archiviert</option></select></Field>{vehicle&&<><Field label="Änderungsart"><select className="input" name="changeType" required>{["Fahrzeug geändert","Nutzerwechsel","Fahrzeug beendet","Versteuerungsmethode geändert","Sonstiger Vorgang"].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Wirksam ab"><input className="input" name="effectiveFrom" type="date" required/></Field></>}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Check name="contractAvailable" label="Vertrag vorhanden" checked={vehicle?.contractAvailable}/><Check name="onePercentRule" label="1-%-Regelung" checked={vehicle?.onePercentRule}/><Check name="logbook" label="Fahrtenbuch" checked={vehicle?.logbook}/><Check name="commuteUse" label="Wohnung–erste Tätigkeitsstätte" checked={vehicle?.commuteUse}/></div>
    <Field label="Rechnungswesenbehandlung"><textarea className="input min-h-20" name="accountingExplanation" defaultValue={vehicle?.accountingExplanation??""}/></Field><Field label="Interner Hinweis"><textarea className="input min-h-20" name="note" defaultValue={vehicle?.note??""}/></Field><button className="button-primary">Fahrzeug speichern</button>
  </form>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-semibold"><span className="mb-1 block">{label}</span>{children}</label>}
function Check({name,label,checked}:{name:string;label:string;checked?:boolean}){return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>}
