import Link from "next/link";
import { AdministrationBreadcrumbs } from "@/app/components/administration-navigation";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatDate, textOrDash } from "@/lib/format";
import { requireUser } from "@/lib/auth";
import { canManageOrdoCampus,canManageStandardTasks } from "@/lib/permissions";
import { redirect } from "next/navigation";
import { formatExecutionPlanning } from "@/lib/task-execution-planning";

export default async function TaskDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ erfolg?: string }> }) {
  const id = Number((await params).id);
  const user=await requireUser();
  const task = Number.isInteger(id) ? await prisma.standardTask.findUnique({ where: { id }, include: { category: true,planningHistory:{orderBy:{occurredAt:"desc"}},knowledgeContentLinks:{include:{knowledgeContent:{include:{areas:{where:{primaryArea:true},include:{knowledgeArea:true}}}}},orderBy:[{mainContent:"desc"},{sortOrder:"asc"}]} } }) : null;
  if (!task) notFound();
  if(!canManageStandardTasks(user)&&!canManageOrdoCampus(user))redirect("/zugriff-verweigert?bereich=Standardaufgaben");
  const success = (await searchParams).erfolg;
  return <div>
    <AdministrationBreadcrumbs section="fachliche-grundlagen" current="Standardaufgabe"/>
    <div className="mb-5"><Link className="text-sm font-semibold text-[var(--color-primary-dark)] hover:underline" href="/standardaufgaben">← Zur Übersicht</Link></div>
    {success && <div role="status" className="mb-5 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">Die Standardaufgabe wurde erfolgreich {success === "angelegt" ? "angelegt" : "gespeichert"}.</div>}
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-sm font-semibold uppercase tracking-wider text-[var(--color-primary)]">{task.taskId}</p><h1 className="text-3xl font-bold">{task.title}</h1></div><div className="flex gap-2">{canManageOrdoCampus(user)&&<Link className="button-primary" href={`/standardaufgaben/${task.id}/campus`}>Wissensverknüpfungen verwalten</Link>}{canManageStandardTasks(user)&&<Link className="button-secondary" href={`/standardaufgaben/${task.id}/bearbeiten`}>Bearbeiten</Link>}</div></header>
    <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Data label="Status" value={task.active ? "Aktiv" : "Inaktiv"} /><Data label="Checklistenart" value={task.checklistType} /><Data label="Kategorie" value={task.category.name} /><Data label="Unterkategorie" value={textOrDash(task.subcategory)} /><Data label="Ausführungsplanung" value={task.checklistType==="Jahresabschluss"?"Jährlich":formatExecutionPlanning(task.rhythm,task.executionMonths)} /><Data label="Aufgabenbereich" value={task.taskArea??"–"} /><Data label="Pflichtaufgabe" value={task.mandatory ? "Ja" : "Nein"} /><Data label="Version" value={task.professionalVersion} /><Data label="Rechtsformgruppen" value={task.legalFormGroups} /><Data label="Gewinnermittlungsarten" value={task.profitDeterminationMethods} /><Data label="Sortierreihenfolge" value={task.sortOrder.toString()} /><Data label="Geändert am" value={formatDate(task.updatedAt)} />
    </dl></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><TextCard title="Arbeitsanweisung" value={task.workInstruction} /><TextCard title="Prüfanweisung" value={task.reviewInstruction} /></section>
    <section className="mt-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Merkmalsbedingungen</h2><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Data label="Kasse" value={task.cashCondition} /><Data label="Lohn" value={task.payrollCondition} /><Data label="Anlagevermögen" value={task.fixedAssetsCondition} /><Data label="Debitoren/Kreditoren" value={task.receivablesPayablesCondition} /><Data label="Darlehen" value={task.loansCondition} /><Data label="Umsatzsteuerpflicht" value={task.vatCondition} /><Data label="Dauerfristverlängerung" value={task.permanentExtensionCondition} /></dl></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><TextCard title="Wissensschlüssel" value={task.knowledgeKey} /><TextCard title="Interne Bemerkung" value={task.internalNote} /></section>
    {task.planningHistory.length>0&&<section className="mt-6 rounded-lg border border-[var(--color-border)] bg-white p-5"><h2 className="text-lg font-semibold">Verlauf der Ausführungsplanung</h2><ul className="mt-3 space-y-2 text-sm">{task.planningHistory.map(entry=><li key={entry.id} className="rounded bg-[var(--color-background)] p-3"><strong>{entry.changedArea}</strong> durch {entry.actorNameSnapshot} am {formatDate(entry.occurredAt)}<div className="text-[var(--color-text-muted)]">{entry.previousValue??"–"} → {entry.newValue??"–"}</div></li>)}</ul></section>}
    <section className="mt-7 rounded-lg border border-[var(--color-border)] bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Verknüpftes Ordo-Campus-Wissen</h2><span className="rounded bg-[var(--color-primary-light)] px-2 py-1 text-xs font-semibold">{task.knowledgeContentLinks.filter(link=>link.knowledgeContent.status==="Aktiv").length} aktiv</span></div><p className="mt-2 text-sm text-[var(--color-text-muted)]">Die Wissensinhalte werden eigenständig im Wissensmanagement gepflegt. Diese Standardaufgabe ist nur ein Anwendungsort.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{task.knowledgeContentLinks.map(link=><Link className="rounded-lg border bg-[var(--color-background)] p-4 hover:border-[var(--color-primary)]" href={`/ordo-campus/wissen/${link.knowledgeContentId}`} key={link.id}><span className="text-xs font-semibold text-[var(--color-primary-dark)]">{link.mainContent?"Hauptinhalt":link.linkType}</span><strong className="mt-1 block">{link.knowledgeContent.title}</strong><span className="mt-1 block text-xs text-[var(--color-text-muted)]">{link.knowledgeContent.areas[0]?.knowledgeArea.title??link.knowledgeContent.status}</span></Link>)}</div>{task.knowledgeContentLinks.length===0&&<p className="mt-4 rounded border border-dashed p-5 text-sm">Noch kein eigenständiger Wissensinhalt verknüpft.</p>}</section>
  </div>;
}
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>; }
function TextCard({ title, value }: { title: string; value: string | null }) { return <article className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-700">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm">{textOrDash(value)}</p></article>; }
