import { prisma } from "../lib/prisma.ts";
import { createAnnualChecklist, createAnnualTaskFromMonthly, reviewAnnualTask, transitionAnnualChecklist, updateAnnualTask } from "../lib/annual-checklist-service.ts";
import type { AuthUser } from "../lib/permissions.ts";

await prisma.annualWorkflowHistory.deleteMany();
await prisma.annualChecklistTask.deleteMany();
await prisma.annualChecklist.deleteMany();
await prisma.customAnnualTask.deleteMany();
await prisma.standardTask.deleteMany({where:{taskId:{startsWith:"JA-TEST-"}}});
const categoryNames=["Abschlussvorbereitung","Bilanz und Bewertung","Anlagevermögen","Forderungen und Verbindlichkeiten","Rückstellungen","Rechnungsabgrenzung","Personal","Steuern","Gesellschaftsrecht","Anhang und Bericht","Offenlegung","Abschlussprüfung","Freigabe und Ausgabe"];
const categories=new Map<string,number>();
for(const [index,name] of categoryNames.entries()){const category=await prisma.taskCategory.upsert({where:{name},update:{active:true},create:{name,description:`Künstliche Jahresabschlusskategorie ${name}.`,sortOrder:200+(index+1)*10}});categories.set(name,category.id)}
for(let index=0;index<24;index++){const category=categoryNames[index%categoryNames.length];await prisma.standardTask.create({data:{taskId:`JA-TEST-${String(index+1).padStart(3,"0")}`,active:true,checklistType:"Jahresabschluss",categoryId:categories.get(category)!,title:`Künstliche stichtagsbezogene Jahresabschlussaufgabe ${index+1}`,workInstruction:"Ausschließlich künstliche Arbeitsanweisung für lokale Tests.",reviewInstruction:"Künstliches Ergebnis fachlich nachvollziehen.",mandatory:index<8,rhythm:"Jährlich",legalFormGroups:index>=16&&index<19?"Kapitalgesellschaft":"Alle",profitDeterminationMethods:index>=20?"Einnahmenüberschussrechnung":"Alle",cashCondition:"Alle",payrollCondition:index===10?"Ja":"Alle",fixedAssetsCondition:index===8?"Ja":"Alle",receivablesPayablesCondition:"Alle",loansCondition:index===22?"Ja":"Alle",vatCondition:"Alle",permanentExtensionCondition:"Alle",sortOrder:(index+1)*10,professionalVersion:"JA-TEST-2026",internalNote:"Ausschließlich künstliche Jahresabschlussaufgabe."}})}
const clients=await prisma.client.findMany({include:{annualProfiles:{where:{calendarYear:2026}}}});
for(const client of clients){const profile=client.annualProfiles[0];if(!profile)continue;for(const year of [2024,2025])await prisma.annualProfile.upsert({where:{clientId_calendarYear:{clientId:client.id,calendarYear:year}},update:{},create:{clientId:client.id,calendarYear:year,legalFormGroup:profile.legalFormGroup,profitDeterminationMethod:profile.profitDeterminationMethod,hasCashRegister:profile.hasCashRegister,hasPayroll:profile.hasPayroll,hasFixedAssets:profile.hasFixedAssets,hasReceivablesPayables:profile.hasReceivablesPayables,hasLoans:profile.hasLoans,subjectToVat:profile.subjectToVat,hasPermanentExtension:profile.hasPermanentExtension}})}
const user=async(username:string):Promise<AuthUser>=>{const value=await prisma.user.findUniqueOrThrow({where:{username},include:{roles:true}});return{id:value.id,fullName:value.fullName,username:value.username,active:value.active,mustChangePassword:value.mustChangePassword,roles:value.roles.map(role=>role.role) as AuthUser["roles"]}};
const maria=await user("maria.muster"),paul=await user("paul.pruefung"),klara=await user("klara.leitung"),max=await user("max.beispiel");
const byNumber=new Map(clients.map(client=>[client.clientNumber,client]));
await prisma.customAnnualTask.create({data:{clientId:byNumber.get("10001")!.id,title:"Künstliche mandantenspezifische Jahresabschlussvorlage",description:"Nur für lokale Tests.",category:"Abschlussvorbereitung",validFromYear:2025,sortOrder:900}});
async function finishMandatory(id:number,actor:AuthUser){for(const task of await prisma.annualChecklistTask.findMany({where:{annualChecklistId:id,mandatorySnapshot:true}}))await updateAnnualTask(task.id,{status:"Erledigt",processingNote:"Künstlich abschließend bearbeitet.",notApplicableReason:""},actor)}
async function ready(id:number,actor:AuthUser){await finishMandatory(id,actor);const item=await prisma.annualChecklist.findUniqueOrThrow({where:{id}});if(item.status==="Offen")await transitionAnnualChecklist(id,"BEGIN",actor);await transitionAnnualChecklist(id,"SUBMIT_REVIEW",actor)}
async function fachlich(id:number,reviewer:AuthUser){await transitionAnnualChecklist(id,"BEGIN_REVIEW",reviewer);for(const task of await prisma.annualChecklistTask.findMany({where:{annualChecklistId:id}}))await reviewAnnualTask(task.id,{reviewStatus:"In Ordnung",reviewNote:"Künstlich geprüft."},reviewer);await transitionAnnualChecklist(id,"PROFESSIONAL_COMPLETE",reviewer)}
const a1=await createAnnualChecklist(byNumber.get("10001")!.id,2025,maria);await transitionAnnualChecklist(a1.id,"BEGIN",maria);
const a1current=await createAnnualChecklist(byNumber.get("10001")!.id,2026,maria);const monthlyPoint=await prisma.checklistTask.findFirst({where:{period:{clientId:byNumber.get("10001")!.id,calendarYear:2026},OR:[{status:"In Folgemonat übertragen"},{status:"In Bearbeitung"}]}});if(monthlyPoint)await createAnnualTaskFromMonthly(a1current.id,monthlyPoint.id,paul);
const a2=await createAnnualChecklist(byNumber.get("10002")!.id,2025,maria);await ready(a2.id,maria);
const a3=await createAnnualChecklist(byNumber.get("10003")!.id,2025,max);await ready(a3.id,max);await fachlich(a3.id,paul);await transitionAnnualChecklist(a3.id,"SUBMIT_RELEASE",paul);
const a4=await createAnnualChecklist(byNumber.get("10004")!.id,2025,maria);await ready(a4.id,maria);await transitionAnnualChecklist(a4.id,"BEGIN_REVIEW",paul);const issue=await prisma.annualChecklistTask.findFirstOrThrow({where:{annualChecklistId:a4.id}});await reviewAnnualTask(issue.id,{reviewStatus:"Rückfrage",reviewNote:"Künstliche Rückfrage zum Jahresabschluss."},paul);await transitionAnnualChecklist(a4.id,"RETURN_REWORK",paul);
const old=await createAnnualChecklist(byNumber.get("10004")!.id,2024,maria);await ready(old.id,maria);await fachlich(old.id,paul);await transitionAnnualChecklist(old.id,"SUBMIT_RELEASE",paul);await transitionAnnualChecklist(old.id,"RELEASE",klara,"Künstliche Freigabe eines älteren Abschlusses.");
await prisma.$disconnect();
console.log("Künstliche Jahresabschluss-Testdaten wurden ergänzt.");
