import { NextResponse } from "next/server";
import { currentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canManageOrdoCampus, canReadCampusReviewerGuidance, canViewAnnualChecklist, canViewClient, canViewPayrollReconciliation } from "@/lib/permissions";

export const dynamic = "force-dynamic";
export async function GET(_request: Request, { params }: { params: Promise<{ kind: string; taskId: string }> }) {
  const user = await currentUser(); if (!user) return NextResponse.json({ error: "Bitte melden Sie sich erneut an." }, { status: 401 });
  const { kind, taskId: raw } = await params; const taskId = Number(raw); if (!Number.isInteger(taskId) || !["monat","jahresabschluss","fibu-lohn"].includes(kind)) return NextResponse.json({ error: "Die Aufgabe wurde nicht gefunden." }, { status: 404 });
  const access = kind === "monat" ? await prisma.checklistTask.findUnique({ where: { id: taskId }, select: { standardTaskId: true, period: { select: { processorUserId: true, reviewerUserId: true, managementUserId: true } } } }).then((task) => task && ({ standardTaskId: task.standardTaskId, topicId: null, allowed: canViewClient(user, task.period) })) : kind === "jahresabschluss" ? await prisma.annualChecklistTask.findUnique({ where: { id: taskId }, select: { standardTaskId: true, annualChecklist: { select: { processorUserId: true, reviewerUserId: true, managementUserId: true } } } }).then((task) => task && ({ standardTaskId: task.standardTaskId, topicId: null, allowed: canViewAnnualChecklist(user, task.annualChecklist) })) : await prisma.payrollReconciliationItem.findUnique({ where: { id: taskId }, select: { sourceTopicId: true, reconciliation: { select: { processorUserId: true, reviewerUserId: true, payrollUserId: true } } } }).then((item) => item && ({ standardTaskId: null, topicId: item.sourceTopicId, allowed: canViewPayrollReconciliation(user, item.reconciliation) }));
  if (!access?.allowed) return NextResponse.json({ error: "Sie dürfen das Wissen zu dieser Aufgabe nicht öffnen." }, { status: 403 });
  const contents = await prisma.knowledgeContent.findMany({ where: { status: "Aktiv", ...(access.standardTaskId ? { taskLinks: { some: { standardTaskId: access.standardTaskId } } } : { payrollTopicLinks: { some: { payrollReconciliationTopicId: access.topicId! } } }) }, include: { taskLinks: { where: access.standardTaskId ? { standardTaskId: access.standardTaskId } : undefined }, payrollTopicLinks: { where: access.topicId ? { payrollReconciliationTopicId: access.topicId } : undefined }, links: { where: { active: true }, orderBy: [{ sortOrder: "asc" }, { title: "asc" }] }, attachments: { where: { status: "Aktiv" }, orderBy: [{ sortOrder: "asc" }, { displayName: "asc" }] }, areas: { where: { primaryArea: true }, include: { knowledgeArea: true } } }, orderBy: [{ title: "asc" }] });
  const showReviewer = canReadCampusReviewerGuidance(user);
  const ordered = contents.sort((a, b) => {
    const aLink = a.taskLinks[0] ?? a.payrollTopicLinks[0];
    const bLink = b.taskLinks[0] ?? b.payrollTopicLinks[0];
    return Number(bLink?.mainContent ?? false) - Number(aLink?.mainContent ?? false) || (aLink?.sortOrder ?? 0) - (bLink?.sortOrder ?? 0) || a.title.localeCompare(b.title, "de");
  });
  return NextResponse.json({ contents: ordered.map((content) => ({ id: content.id, title: content.title, status: content.status, shortDescription: content.shortDescription, objective: content.objective, mainContent: content.mainContent, workingGuidance: content.workingGuidance, firmStandard: content.firmStandard, reviewerGuidance: showReviewer ? content.reviewerGuidance : null, typicalErrors: content.typicalErrors, internalHints: content.internalHints, primaryArea: content.areas[0]?.knowledgeArea.title ?? null, main: Boolean(content.taskLinks[0]?.mainContent ?? content.payrollTopicLinks[0]?.mainContent), contextHint: content.taskLinks[0]?.contextHint ?? content.payrollTopicLinks[0]?.contextHint ?? null, links: content.links, attachments: content.attachments.map((a) => ({ id:a.id,displayName:a.displayName,fileExtension:a.fileExtension,fileSizeBytes:a.fileSizeBytes,description:a.description })) })), canEdit: canManageOrdoCampus(user), editHref: access.standardTaskId ? `/verwaltung/wissensmanagement?aufgabe=${access.standardTaskId}` : `/verwaltung/wissensmanagement?thema=${access.topicId}` });
}
